from typing import Optional, Dict

class DrugNameResolver:
    """
    Resolves brand names and alternative phrasings to canonical generic names
    for the 105 drugs supported by MedRef.
    """
    
    BRAND_TO_GENERIC: Dict[str, str] = {
        "edarbi": "azilsartan", "inspra": "eplerenone", "corlanor": "ivabradine", "ranexa": "ranolazine",
        "effient": "prasugrel", "brilinta": "ticagrelor", "angiomax": "bivalirudin", "primacor": "milrinone",
        "cardene": "nicardipine", "cleviprex": "clevidipine", "trandate": "labetalol", "brevibloc": "esmolol",
        "minipress": "prazosin", "hytrin": "terazosin", "cardura": "doxazosin", "merrem": "meropenem", "invanz": "ertapenem",
        "primaxin": "imipenem", "maxipime": "cefepime", "teflaro": "ceftaroline", "zerbaxa": "ceftolozane", "avycaz": "avibactam",
        "coly-mycin": "colistin", "tygacil": "tigecycline", "cubicin": "daptomycin", "zyvox": "linezolid", "sivextro": "tedizolid",
        "dalvance": "dalbavancin", "cresemba": "isavuconazole", "nofil": "posaconazole", "meronem": "meropenem", "cifran": "ciprofloxacin",
        "oflox": "ofloxacin", "zenflox": "ofloxacin", "mahacef": "cefixime", "ceftas": "cefixime", "taxim": "cefotaxime",
        "taxim-o": "cefixime", "zipod": "cefpodoxime", "goodcef": "cefpodoxime", "macrowin": "azithromycin", "aziwok": "azithromycin",
        "zocon": "fluconazole", "forcan": "fluconazole", "canditral": "itraconazole", "ityza": "itraconazole", "mounjaro": "tirzepatide",
        "zepbound": "tirzepatide", "victoza": "liraglutide", "saxenda": "liraglutide", "trulicity": "dulaglutide", "byetta": "exenatide",
        "invokana": "canagliflozin", "steglatro": "ertugliflozin", "januvia": "sitagliptin", "onglyza": "saxagliptin", "tradjenta": "linagliptin",
        "nesina": "alogliptin", "actos": "pioglitazone", "avandia": "rosiglitazone", "prio": "pioglitazone", "pioz": "pioglitazone",
        "arcapta": "indacaterol", "anoro": "umeclidinium", "seebri": "glycopyrrolate", "tudorza": "aclidinium", "alvesco": "ciclesonide",
        "asmanex": "mometasone", "flovent": "fluticasone", "pulmicort": "budesonide", "singulair": "montelukast", "aciphex": "dexlansoprazole",
        "aciphex-ez": "rabeprazole", "prazocid": "rabeprazole", "pariet": "rabeprazole", "carafate": "sucralfate", "cytotec": "misoprostol",
        "linzess": "linaclotide", "emend": "aprepitant", "aloxi": "palonosetron", "kytril": "granisetron", "keytruda": "pembrolizumab",
        "opdivo": "nivolumab", "tecentriq": "atezolizumab", "imfinzi": "durvalumab", "yervoy": "ipilimumab", "mabthera": "rituximab",
        "herceptin": "trastuzumab", "avastin": "bevacizumab", "erbitux": "cetuximab", "gleevec": "imatinib", "sprycel": "dasatinib",
        "tasigna": "nilotinib", "diprivan": "propofol", "precedex": "dexmedetomidine", "ativan": "lorazepam", "ketalar": "ketamine",
        "nimbex": "cisatracurium", "zemuron": "rocuronium", "bridion": "sugammadex", "keppra": "levetiracetam", "vimpat": "lacosamide",
        "otezla": "apremilast", "xeljanz": "tofacitinib", "olumiant": "baricitinib", "rinvoq": "upadacitinib", "jyseleca": "filgotinib",
        "cibinqo": "abrocitinib", "sotyktu": "deucravacitinib", "cosentyx": "secukinumab", "taltz": "ixekizumab", "siliq": "brodalumab",
        "tremfya": "guselkumab", "ilumya": "tildrakizumab", "skyrizi": "risankizumab", "stelara": "ustekinumab", "entyvio": "vedolizumab",
        "tysabri": "natalizumab", "zeposia": "ozanimod", "ponvory": "ponesimod", "mayzent": "siponimod", "gilenya": "fingolimod",
        "lemtrada": "alemtuzumab", "ocrevus": "ocrelizumab", "kesimpta": "ofatumumab", "briumvi": "ublituximab", "mavenclad": "cladribine",
        # Core Brand to Generic Mappings
        "prinivil": "lisinopril",
        "zestril": "lisinopril",
        "lipitor": "atorvastatin",
        "glucophage": "metformin",
        "fortamet": "metformin",
        "glumetza": "metformin",
        "amoxil": "amoxicillin",
        "novamox": "amoxicillin",
        "advil": "ibuprofen",
        "motrin": "ibuprofen",
        "cozaar": "losartan",
        "coumadin": "warfarin",
        "jantoven": "warfarin",
        "ventolin": "albuterol",
        "proair": "albuterol",
        "proventil": "albuterol",
        "norvasc": "amlodipine",
        "synthroid": "levothyroxine",
        "levoxyl": "levothyroxine",
        "unithroid": "levothyroxine",
        "neurontin": "gabapentin",
        "prilosec": "omeprazole",
        "lopressor": "metoprolol",
        "toprol": "metoprolol",
        "microzide": "hydrochlorothiazide",
        "zocor": "simvastatin",
        "zoloft": "sertraline",
        "singulair": "montelukast",
        "lexapro": "escitalopram",
        "tylenol": "acetaminophen",
        "lasix": "furosemide",
        "flonase": "fluticasone",
        "flovent": "fluticasone",
        "wellbutrin": "bupropion",
        "zyban": "bupropion",
        "cymbalta": "duloxetine",
        "protonix": "pantoprazole",
        "deltasone": "prednisone",
        "crestor": "rosuvastatin",
        "flomax": "tamsulosin",
        "celexa": "citalopram",
        "mobic": "meloxicam",
        "zyloprim": "allopurinol",
        "aloprim": "allopurinol",
        "xanax": "alprazolam",
        "klonopin": "clonazepam",
        "valium": "diazepam",
        "ativan": "lorazepam",
        "ambien": "zolpidem",
        "coreg": "carvedilol",
        "aldactone": "spironolactone",
        "vasotec": "enalapril",
        "altace": "ramipril",
        "diovan": "valsartan",
        "tenormin": "atenolol",
        "inderal": "propranolol",
        "apresoline": "hydralazine",
        "catapres": "clonidine",
        "pravachol": "pravastatin",
        "mevacor": "lovastatin",
        "tricor": "fenofibrate",
        "antara": "fenofibrate",
        "lopid": "gemfibrozil",
        "zetia": "ezetimibe",
        "colcrys": "colchicine",
        "mitigare": "colchicine",
        "rheumatrex": "methotrexate",
        "trexall": "methotrexate",
        "plaquenil": "hydroxychloroquine",
        "imuran": "azathioprine",
        "neoral": "cyclosporine",
        "sandimmune": "cyclosporine",
        "gengraf": "cyclosporine",
        "prograf": "tacrolimus",
        "millipred": "prednisolone",
        "orapred": "prednisolone",
        "decadron": "dexamethasone",
        "medrol": "methylprednisolone",
        "pulmicort": "budesonide",
        "rhinocort": "budesonide",
        "foradil": "formoterol",
        "serevent": "salmeterol",
        "spiriva": "tiotropium",
        "atrovent": "ipratropium",
        "zyrtec": "cetirizine",
        "claritin": "loratadine",
        "allegra": "fexofenadine",
        "benadryl": "diphenhydramine",
        "vistaril": "hydroxyzine",
        "atarax": "hydroxyzine",
        "phenergan": "promethazine",
        "zofran": "ondansetron",
        "reglan": "metoclopramide",
        "imodium": "loperamide",
        "pepcid": "famotidine",
        "tagamet": "cimetidine",
        "nexium": "esomeprazole",
        "prevacid": "lansoprazole",
        "aciphex": "rabeprazole",
        "cytotec": "misoprostol",
        "azulfidine": "sulfasalazine",
        "lialda": "mesalamine",
        "asacol": "mesalamine",
        "pentasa": "mesalamine",
        "zithromax": "azithromycin",
        "biaxin": "clarithromycin",
        "erythrocin": "erythromycin",
        "vibramycin": "doxycycline",
        "doryx": "doxycycline",
        "minocin": "minocycline",
        "solodyn": "minocycline",
        "sumycin": "tetracycline",
        "keflex": "cephalexin",
        "omnicef": "cefdinir",
        "ceftin": "cefuroxime",
        "cipro": "ciprofloxacin",
        "levaquin": "levofloxacin",
        "avelox": "moxifloxacin",
        "flagyl": "metronidazole",
        "cleocin": "clindamycin",
        "zyvox": "linezolid",
        "vancocin": "vancomycin",
        "macrobid": "nitrofurantoin",
        "macrodantin": "nitrofurantoin",
        "primsol": "trimethoprim",
        "diflucan": "fluconazole",
        "nizoral": "ketoconazole",
        "sporanox": "itraconazole",
        "lamisil": "terbinafine",
        "zovirax": "acyclovir",
        "valtrex": "valacyclovir",
        "tamiflu": "oseltamivir",
        "ozempic": "semaglutide",
        "wegovy": "semaglutide",
        "mounjaro": "tirzepatide",
        "zepbound": "tirzepatide",
        "jardiance": "empagliflozin",
        "farxiga": "dapagliflozin",
        "invokana": "canagliflozin",
        "victoza": "liraglutide",
        "saxenda": "liraglutide",
        "trulicity": "dulaglutide",
        "januvia": "sitagliptin",
        "tradjenta": "linagliptin",
        "onglyza": "saxagliptin",
        "nesina": "alogliptin",
        "actos": "pioglitazone",
        "avandia": "rosiglitazone",
        "precose": "acarbose",
        "glyset": "miglitol",
        "amaryl": "glimepiride",
        "glucotrol": "glipizide",
        "micronase": "glyburide",
        "diabeta": "glyburide",
        "prandin": "repaglinide",
        "starlix": "nateglinide",
        "humalog": "insulin lispro",
        "novolog": "insulin aspart",
        "apidra": "insulin glulisine",
        "lantus": "insulin glargine",
        "toujeo": "insulin glargine",
        "basaglar": "insulin glargine",
        "levemir": "insulin detemir",
        "tresiba": "insulin degludec",
        # Specialty & Oncology Mappings
        "eliquis": "apixaban",
        "xarelto": "rivaroxaban",
        "pradaxa": "dabigatran",
        "savaysa": "edoxaban",
        "plavix": "clopidogrel",
        "brilinta": "ticagrelor",
        "effient": "prasugrel",
        "entresto": "sacubitril_valsartan",
        "keytruda": "pembrolizumab",
        "opdivo": "nivolumab",
        "tecentriq": "atezolizumab",
        "imfinzi": "durvalumab",
        "yervoy": "ipilimumab",
        "herceptin": "trastuzumab",
        "perjeta": "pertuzumab",
        "avastin": "bevacizumab",
        "rituxan": "rituximab",
        "erbitux": "cetuximab",
        "gleevec": "imatinib",
        "sprycel": "dasatinib",
        "tasigna": "nilotinib",
        "tagrisso": "osimertinib",
        "tarceva": "erlotinib",
        "alecensa": "alectinib",
        "imbruvica": "ibrutinib",
        "calquence": "acalabrutinib",
        "brukinsa": "zanubrutinib",
        "venclexta": "venetoclax",
        "ibrance": "palbociclib",
        "kisqali": "ribociclib",
        "verzenio": "abemaciclib",
        "lynparza": "olaparib",
        "zejula": "niraparib",
        "rubraca": "rucaparib",
        "humira": "adalimumab",
        "enbrel": "etanercept",
        "remicade": "infliximab",
        "cimzia": "certolizumab",
        "simponi": "golimumab",
        "actemra": "tocilizumab",
        "cosentyx": "secukinumab",
        "taltz": "ixekizumab",
        "stelara": "ustekinumab",
        "tremfya": "guselkumab",
        "skyrizi": "risankizumab",
        "benlysta": "belimumab",
        "orencia": "abatacept",
        "cellcept": "mycophenolate_mofetil",
        "uloric": "febuxostat",
        # --- Critical missing brand/generic mappings ---
        "kerendia": "finerenone",
        "inspra": "eplerenone",
        "pacerone": "amiodarone",
        "cordarone": "amiodarone",
        "nexterone": "amiodarone",
        "lanoxin": "digoxin",
        "digitek": "digoxin",
        "levophed": "norepinephrine",
        "zosyn": "piperacillin",
        "merrem": "meropenem",
        "primaxin": "imipenem",
        "invanz": "ertapenem",
        "rocephin": "ceftriaxone",
        "ancef": "cefazolin",
        "maxipime": "cefepime",
        "fortaz": "ceftazidime",
        "cubicin": "daptomycin",
        "tygacil": "tigecycline",
        "naprosyn": "naproxen",
        "aleve": "naproxen",
        "celebrex": "celecoxib",
        "indocin": "indomethacin",
        "toradol": "ketorolac",
        "lovenox": "enoxaparin",
        "arixtra": "fondaparinux",
        "diprivan": "propofol",
        "versed": "midazolam",
        "sublimaze": "fentanyl",
        "dilaudid": "hydromorphone",
        "ultram": "tramadol",
        "precedex": "dexmedetomidine",
        "zemuron": "rocuronium",
        "anectine": "succinylcholine",
        "norcuron": "vecuronium",
        "procardia": "nifedipine",
        "adalat": "nifedipine",
        "cardizem": "diltiazem",
        "tiazac": "diltiazem",
        "calan": "verapamil",
        "isoptin": "verapamil",
        "dupixent": "dupilumab",
        "nucala": "mepolizumab",
        "fasenra": "benralizumab",
        "tezspire": "tezepelumab",
        "xeljanz": "tofacitinib",
        "olumiant": "baricitinib",
        "lipaglyn": "saroglitazar",
        "crocin": "paracetamol",
        "calpol": "paracetamol",
        "dolo": "paracetamol",
        "dolo 650": "paracetamol",
        "dolo650": "paracetamol",
        "pacimol": "paracetamol",
        "pcm": "paracetamol",
        "panadol": "paracetamol",
        "glycomet": "metformin",
        "cetapin": "metformin",
        "gluformin": "metformin",
        "clavam": "amoxicillin_clavulanate",
        "moxikind-cv": "amoxicillin_clavulanate",
        "moxikind cv": "amoxicillin_clavulanate",
        "augmentin": "amoxicillin_clavulanate",
        "pan-d": "pantoprazole_domperidone",
        "pan d": "pantoprazole_domperidone",
        "pantocid": "pantoprazole",
        "pantocid-d": "pantoprazole_domperidone",
        "razo": "rabeprazole",
        "rabekind": "rabeprazole",
        "veloz": "rabeprazole",
        "telma": "telmisartan",
        "telma-h": "telmisartan",
        "telmikind": "telmisartan",
        "telista": "telmisartan",
        "amlong": "amlodipine",
        "stamlo": "amlodipine",
        "cilacar": "cilnidipine",
        "cilaheart": "cilnidipine",
        "metolar": "metoprolol",
        "metolar-xr": "metoprolol",
        "nebicard": "nebivolol",
        "nebi": "nebivolol",
        "cardivas": "carvedilol",
        "rosuvas": "rosuvastatin",
        "razel": "rosuvastatin",
        "atorva": "atorvastatin",
        "atocor": "atorvastatin",
        "tenepride": "teneligliptin",
        "zita-met": "sitagliptin_metformin",
        "galvus": "vildagliptin",
        "galvus-met": "vildagliptin",
        "janumet": "sitagliptin_metformin",
        "zoryl": "glimepiride",
        "amaryl": "glimepiride",
        "glynase": "glipizide",
        "taxim-o": "cefixime",
        "mahacef": "cefixime",
        "zipod": "cefpodoxime",
        "monocepht": "ceftriaxone",
        "monocef": "ceftriaxone",
        "oframax": "ceftriaxone",
        "magnex": "cefoperazone_sulbactam",
        "pipzo": "piperacillin_tazobactam",
        "meronem": "meropenem",
        "merocrit": "meropenem",
        "faropen": "faropenem",
        "linospan": "linezolid",
        "lizolid": "linezolid",
        "dapto": "daptomycin",
        "vancocin": "vancomycin",
        "vancogen": "vancomycin",
        "niftas": "nitrofurantoin",
        "norflox": "norfloxacin",
        "zocon": "fluconazole",
        "itrasys": "itraconazole",
        "canditral": "itraconazole",
        "ambisome": "amphotericin_b",
        "azithral": "azithromycin",
        "aaz": "azithromycin",
        "zady": "azithromycin",
        "claribid": "clarithromycin",
        "klacid": "clarithromycin",
        "doxy-1": "doxycycline",
        "monodox": "doxycycline",
        "nucoxia": "etoricoxib",
        "etoshine": "etoricoxib",
        "zerodol": "aceclofenac",
        "zerodol-p": "aceclofenac",
        "zerodol-sp": "aceclofenac",
        "hifenac": "aceclofenac",
        "ultracet": "tramadol",
        "tramazac": "tramadol",
        "cyclopam": "dicyclomine",
        "drotin": "drotaverine",
        "spasmonil": "dicyclomine",
        "duphalac": "lactulose",
        "rifagut": "rifaximin",
        "mesacol": "mesalamine",
        "foracort": "formoterol_budesonide",
        "seretide": "salmeterol_fluticasone",
        "levolin": "levosalbutamol",
        "asthalin": "albuterol",
        "deriphyllin": "theophylline",
        "citistar": "citicoline",
        "stugeron": "cinnarizine",
        "vertin": "betahistine",
        "levipil": "levetiracetam",
        "epitril": "clonazepam",
        "lonazep": "clonazepam",
        "frisium": "clobazam",
        "valparin": "sodium_valproate",
        "encorate": "divalproex",
        "sizodon": "risperidone",
        "oleanz": "olanzapine",
        "seroquin": "quetiapine",
        "qutan": "quetiapine",
        "nexito": "escitalopram",
        "clonotril": "clonazepam",
        "etilaam": "etizolam",
        "etizola": "etizolam",
        "alprax": "alprazolam",
        "restyl": "alprazolam",
        "urimax": "tamsulosin",
        "silodal": "silodosin",
        "dutas": "dutasteride",
        "manforce": "sildenafil",
        "megalis": "tadalafil",
        "toptada": "tadalafil",
        "shelcal": "calcium_vitamin_d3",
        "orofer": "iron_sucrose"
    }

    GENERIC_NAMES = {"lisinopril", "atorvastatin", "metformin", "amoxicillin", "ibuprofen",
        "losartan", "warfarin", "albuterol", "amlodipine", "levothyroxine",
        "gabapentin", "omeprazole", "metoprolol", "hydrochlorothiazide",
        "simvastatin", "sertraline", "montelukast", "escitalopram",
        "acetaminophen", "furosemide", "fluticasone", "bupropion",
        "duloxetine", "pantoprazole", "prednisone", "rosuvastatin",
        "tamsulosin", "citalopram", "meloxicam", "allopurinol",
        "alprazolam", "clonazepam", "diazepam", "lorazepam", "zolpidem",
        "carvedilol", "spironolactone", "enalapril", "ramipril",
        "valsartan", "atenolol", "propranolol", "hydralazine", "clonidine",
        "pravastatin", "lovastatin", "fenofibrate", "gemfibrozil",
        "ezetimibe", "colchicine", "methotrexate", "hydroxychloroquine",
        "azathioprine", "cyclosporine", "tacrolimus", "prednisolone",
        "dexamethasone", "methylprednisolone", "budesonide", "formoterol",
        "salmeterol", "tiotropium", "ipratropium", "cetirizine",
        "loratadine", "fexofenadine", "diphenhydramine", "hydroxyzine",
        "promethazine", "ondansetron", "metoclopramide", "loperamide",
        "famotidine", "cimetidine", "esomeprazole", "lansoprazole",
        "rabeprazole", "misoprostol", "sulfasalazine", "mesalamine",
        "azithromycin", "clarithromycin", "erythromycin", "doxycycline",
        "minocycline", "tetracycline", "cephalexin", "cefdinir",
        "cefuroxime", "ciprofloxacin", "levofloxacin", "moxifloxacin",
        "metronidazole", "clindamycin", "linezolid", "vancomycin",
        "nitrofurantoin", "trimethoprim", "fluconazole", "ketoconazole",
        "itraconazole", "terbinafine", "acyclovir", "valacyclovir",
        "oseltamivir", "semaglutide", "tirzepatide", "empagliflozin",
        "dapagliflozin", "canagliflozin", "liraglutide", "dulaglutide",
        "sitagliptin", "linagliptin", "saxagliptin", "alogliptin",
        "pioglitazone", "rosiglitazone", "acarbose", "miglitol",
        "glimepiride", "glipizide", "glyburide", "repaglinide",
        "nateglinide", "insulin lispro", "insulin aspart", "insulin glulisine",
        "insulin glargine", "insulin detemir", "insulin degludec",
        # --- Critical newer/missing drugs ---
        "finerenone", "eplerenone",
        "amiodarone", "digoxin", "flecainide", "dronedarone",
        "norepinephrine", "epinephrine", "dopamine", "vasopressin", "dobutamine",
        "piperacillin", "tazobactam", "meropenem", "imipenem", "ertapenem",
        "ceftriaxone", "cefazolin", "cefepime", "ceftazidime",
        "daptomycin", "tigecycline", "colistin",
        "naproxen", "celecoxib", "indomethacin", "ketorolac",
        "heparin", "enoxaparin", "fondaparinux",
        "rivaroxaban", "apixaban", "dabigatran", "edoxaban",
        "clopidogrel", "ticagrelor", "prasugrel",
        "morphine", "fentanyl", "oxycodone", "hydromorphone", "tramadol",
        "midazolam", "propofol", "ketamine", "dexmedetomidine",
        "rocuronium", "succinylcholine", "vecuronium",
        "nifedipine", "diltiazem", "verapamil",
        "sacubitril", "ivabradine", "isosorbide",
        "dupilumab", "mepolizumab", "benralizumab", "tezepelumab",
        "rituximab", "tocilizumab", "baricitinib", "tofacitinib",
        "pembrolizumab", "nivolumab", "atezolizumab",
        "saroglitazar",
        "acebrophylline",
        "aceclofenac",
        "acetaminophen",
        "acyclovir",
        "adalimumab",
        "alendronate",
        "alfacalcidol",
        "alfuzosin",
        "alprazolam",
        "amisulpride",
        "amoxicillin_clavulanate",
        "amphotericin_b",
        "anidulafungin",
        "apremilast",
        "aripiprazole",
        "atorvastatin_fenofibrate",
        "avanafil",
        "azilsartan",
        "azithromycin",
        "baclofen",
        "baricitinib",
        "belimumab",
        "benidipine",
        "betahistine",
        "bisoprolol",
        "blonanserin",
        "brexpiprazole",
        "brivaracetam",
        "bromocriptine",
        "budesonide",
        "bupropion",
        "cabergoline",
        "calcitriol",
        "cariprazine",
        "carisoprodol",
        "carvedilol",
        "caspofungin",
        "cefixime",
        "cefoperazone_sulbactam",
        "ceftriaxone",
        "chlordiazepoxide",
        "cilnidipine",
        "cilostazol",
        "cinnarizine",
        "citicoline",
        "clarithromycin",
        "clindamycin",
        "clobazam",
        "clonazepam",
        "clopidogrel_aspirin",
        "clozapine",
        "colistin",
        "cyclobenzaprine",
        "dapagliflozin_metformin",
        "dapoxetine",
        "daptomycin",
        "darbepoetin",
        "darifenacin",
        "denosumab",
        "desvenlafaxine",
        "divalproex",
        "donepezil",
        "doripenem",
        "doxazosin",
        "doxofylline",
        "doxycycline",
        "drotaverine",
        "duloxetine",
        "dutasteride",
        "edaravone",
        "empagliflozin_linagliptin",
        "entecavir",
        "erythropoietin",
        "escitalopram",
        "etanercept",
        "etizolam",
        "etoricoxib",
        "faropenem",
        "favipiravir",
        "fenofibrate",
        "ferric_carboxymaltose",
        "ferrous_ascorbate",
        "fimasartan",
        "finasteride",
        "flunarizine",
        "fluoxetine",
        "fluvoxamine",
        "folic_acid",
        "formoterol_budesonide",
        "fosfomycin",
        "galantamine",
        "ganciclovir",
        "gemigliptin",
        "gliclazide",
        "glimepiride_metformin",
        "glimepiride_pioglitazone",
        "glycopyrrolium",
        "guselkumab",
        "haloperidol",
        "hydroxychloroquine",
        "indacaterol",
        "infliximab",
        "iron_sucrose",
        "isavuconazole",
        "isosorbide_mononitrate",
        "itraconazole",
        "ivabradine",
        "ixekizumab",
        "lacosamide",
        "lactulose",
        "leflunomide",
        "levetiracetam",
        "levofloxacin",
        "levosulpiride",
        "linezolid",
        "lorazepam",
        "lornoxicam",
        "losartan_hydrochlorothiazide",
        "lurasidone",
        "mebeverine",
        "memantine",
        "meropenem",
        "mesalamine",
        "methotrexate",
        "methylcobalamin",
        "metoprolol_succinate",
        "metoprolol_tartrate",
        "micafungin",
        "miglitol",
        "minocycline",
        "mirabegron",
        "mirtazapine",
        "misoprostol",
        "mitiglinide",
        "molnupiravir",
        "moxifloxacin",
        "nebivolol",
        "nicorandil",
        "nintedanib",
        "nirmatrelvir_ritonavir",
        "nitrofurantoin",
        "norfloxacin",
        "obeticholic_acid",
        "ofloxacin",
        "olanzapine",
        "olmesartan",
        "oxcarbazepine",
        "oxybutynin",
        "pantoprazole_domperidone",
        "paracetamol",
        "paroxetine",
        "perampanel",
        "piperacillin_tazobactam",
        "piracetam",
        "pirfenidone",
        "piroxicam",
        "polyethylene_glycol",
        "polymyxin_b",
        "posaconazole",
        "pramlintide",
        "prasugrel",
        "prochlorperazine",
        "prulifloxacin",
        "pyridoxine",
        "quetiapine",
        "rabeprazole_itopride",
        "remdesivir",
        "remogliflozin",
        "repaglinide",
        "ribavirin",
        "rifaximin",
        "risankizumab",
        "risedronate",
        "risperidone",
        "rituximab",
        "rosuvastatin_ezetimibe",
        "roxithromycin",
        "rufinamide",
        "sacubitril_valsartan",
        "salmeterol_fluticasone",
        "sarilumab",
        "saroglitazar",
        "secukinumab",
        "semaglutide",
        "sertraline",
        "sildenafil",
        "silodosin",
        "sitagliptin_metformin",
        "sodium_valproate",
        "sofosbuvir",
        "solifenacin",
        "sucralfate",
        "sulfasalazine",
        "tadalafil",
        "tamsulosin",
        "tapentadol",
        "tedizolid",
        "teicoplanin",
        "telmisartan_amlodipine",
        "teneligliptin",
        "tenofovir",
        "teriparatide",
        "thiamine",
        "thiocolchicoside",
        "ticagrelor",
        "tigecycline",
        "tirzepatide",
        "tizanidine",
        "tocilizumab",
        "tofacitinib",
        "tolperisone",
        "tolterodine",
        "topiramate",
        "tramadol",
        "trazodone",
        "trimetazidine",
        "upadacitinib",
        "ursodeoxycholic_acid",
        "ustekinumab",
        "valacyclovir",
        "valganciclovir",
        "vancomycin",
        "vardenafil",
        "velpatasvir",
        "venlafaxine",
        "vericiguat",
        "vigabatrin",
        "vilanterol_fluticasone",
        "vildagliptin",
        "voglibose",
        "voriconazole",
        "vortioxetine",
        "zoledronic_acid",
        "zolpidem",
        "zonisamide",
        "zopiclone"
    }

    _initialized: bool = False

    @classmethod
    def _ensure_initialized(cls):
        """
        Dynamically load MASTER_DRUG_INDEX.json to populate all 500 generic and brand names.
        """
        if cls._initialized:
            return

        import os, json
        possible_paths = [
            os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "ingestion", "data", "MASTER_DRUG_INDEX.json"),
            os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))), "docs", "MASTER_DRUG_INDEX.json"),
        ]

        for path in possible_paths:
            if os.path.exists(path):
                try:
                    with open(path, "r", encoding="utf-8") as f:
                        data = json.load(f)
                    for drug_key, entry in data.items():
                        gen_name = entry.get("generic", "").lower().strip()
                        if gen_name:
                            cls.GENERIC_NAMES.add(gen_name)
                            cls.GENERIC_NAMES.add(drug_key.lower().strip())
                        for b in entry.get("brands", []):
                            b_clean = b.lower().strip()
                            if b_clean:
                                cls.BRAND_TO_GENERIC[b_clean] = gen_name or drug_key
                    break
                except Exception:
                    pass

        cls._initialized = True

    @classmethod
    def resolve(cls, query_text: str) -> Optional[str]:
        """
        Scan the query text for drug brand names or generic names.
        Returns the canonical lowercase generic name if found, otherwise None.
        """
        cls._ensure_initialized()
        if not query_text:
            return None

        cls._ensure_initialized()
            
        words = [w.strip("?,.:;!\"'()[]{}").lower() for w in query_text.split()]
        
        # 1. Direct match check on individual words or bigrams
        for word in words:
            if word in DrugNameResolver.GENERIC_NAMES:
                return word
            if word in DrugNameResolver.BRAND_TO_GENERIC:
                return DrugNameResolver.BRAND_TO_GENERIC[word]
                
        # 2. Check for multi-word generic match or substring match (e.g. "methylprednisolone")
        query_lower = query_text.lower()
        for generic in DrugNameResolver.GENERIC_NAMES:
            if generic in query_lower:
                return generic
                
        for brand, generic in DrugNameResolver.BRAND_TO_GENERIC.items():
            if brand in query_lower:
                return generic
                
        return None

# Auto-initialize all 500 canonical drugs on module import
DrugNameResolver._ensure_initialized()
