from typing import Optional, Dict

class DrugNameResolver:
    """
    Resolves brand names and alternative phrasings to canonical generic names
    for the 105 drugs supported by MedRef.
    """
    
    BRAND_TO_GENERIC: Dict[str, str] = {
        "avycaz": "ceftazidime_avibactam", "zerbaxa": "ceftolozane_tazobactam", "vabomere": "meropenem_vaborbactam",
        "recarbrio": "imipenem_cilastatin_relebactam", "fetroja": "cefiderocol", "xenleta": "lefamulin", "zemdri": "plazomicin",
        "dificid": "fidaxomicin", "zinplava": "bezlotoxumab", "livtencity": "maribavir", "prevymis": "letermovir",
        "brexafemme": "ibrexafungerp", "rezzayo": "rezafungin", "xacduro": "sulbactam_durlobactam", "piqray": "alpelisib",
        "verzenio": "abemaciclib", "ibrance": "palbociclib", "kisqali": "ribociclib", "lynparza": "olaparib", "rubraca": "rucaparib",
        "zejula": "niraparib", "talzenna": "talazoparib", "braftovi": "encorafenib", "tafinlar": "dabrafenib", "zelboraf": "vemurafenib",
        "mektovi": "binimetinib", "mekinist": "trametinib", "cotellic": "cobimetinib", "koselugo": "selumetinib", "tabrecta": "capmatinib",
        "tepmetko": "tepotinib", "retevmo": "selpercatinib", "gavreto": "pralsetinib", "lumakras": "sotorasib", "krazati": "adagrasib",
        "lytgobi": "futibatinib", "balversa": "erdafitinib", "pemazyre": "pemigatinib", "tukysa": "tucatinib", "nerlynx": "neratinib",
        "tykerb": "lapatinib", "brukinsa": "zanubrutinib", "calquence": "acalabrutinib", "imbruvica": "ibrutinib", "jaypirca": "pirtobrutinib",
        "venclexta": "venetoclax", "rexulti": "brexpiprazole", "vraylar": "cariprazine", "caplyta": "lumateperone", "nuplazid": "pimavanserin",
        "fanapt": "iloperidone", "saphris": "asenapine", "invega": "paliperidone", "austedo": "deutetrabenazine", "ingrezza": "valbenazine",
        "xenazine": "tetrabenazine", "wakix": "pitolisant", "sunosi": "solriamfetol", "provigil": "modafinil", "nuvigil": "armodafinil",
        "xyrem": "sodium_oxybate", "xywav": "calcium_magnesium_potassium_sodium_oxybates", "nurtec": "rimegepant", "qulipta": "atogepant",
        "ubrelvy": "ubrogepant", "zavzpret": "zavegepant", "vyepti": "eptinezumab", "emgality": "galcanezumab", "ajovy": "fremanezumab",
        "aimovig": "erenumab",
        "edarbi": "azilsartan", "inspra": "eplerenone", "corlanor": "ivabradine", "ranexa": "ranolazine",
        "effient": "prasugrel", "brilinta": "ticagrelor", "angiomax": "bivalirudin", "primacor": "milrinone",
        "cardene": "nicardipine", "cleviprex": "clevidipine", "trandate": "labetalol", "brevibloc": "esmolol",
        "minipress": "prazosin", "hytrin": "terazosin", "cardura": "doxazosin", "merrem": "meropenem", "invanz": "ertapenem",
        "primaxin": "imipenem", "maxipime": "cefepime", "teflaro": "ceftaroline", "zerbaxa": "ceftolozane", "avycaz": "avibactam",
        "coly-mycin": "colistin", "tygacil": "tigecycline", "cubicin": "daptomycin", "zyvox": "linezolid", "sivextro": "tedizolid",
        "dalvance": "dalbavancin", "cresemba": "isavuconazole", "nofil": "posaconazole", "meronem": "meropenem", "cifran": "ciprofloxacin",
        "oflox": "ofloxacin", "zenflox": "ofloxacin", "mahacef": "cefixime", "ceftas": "cefixime", "taxim": "cefotaxime",
        "taxim-o": "cefixime", "zipod": "cefpodoxime", "goodcef": "cefpodoxime", "macrowin": "azithromycin", "aziwok": "azithromycin",
        "zocon": "fluconazole", "forcan": "fluconazole", "canditral": "itraconazole", "ityza": "itraconazole", "mounjaro": "tirzepatide",
        "zepbound": "tirzepatide", "victoza": "liraglutide", "saxenda": "liraglutide", "trulicity": "dulaglutide", "byetta": "exenatide",
        "invokana": "canagliflozin", "steglatro": "ertugliflozin", "januvia": "sitagliptin", "onglyza": "saxagliptin", "tradjenta": "linagliptin",
        "nesina": "alogliptin", "actos": "pioglitazone", "avandia": "rosiglitazone", "prio": "pioglitazone", "pioz": "pioglitazone",
        "arcapta": "indacaterol", "anoro": "umeclidinium", "seebri": "glycopyrrolate", "tudorza": "aclidinium", "alvesco": "ciclesonide",
        "asmanex": "mometasone", "flovent": "fluticasone", "pulmicort": "budesonide", "singulair": "montelukast", "aciphex": "dexlansoprazole",
        "aciphex-ez": "rabeprazole", "prazocid": "rabeprazole", "pariet": "rabeprazole", "carafate": "sucralfate", "cytotec": "misoprostol",
        "linzess": "linaclotide", "emend": "aprepitant", "aloxi": "palonosetron", "kytril": "granisetron", "keytruda": "pembrolizumab",
        "opdivo": "nivolumab", "tecentriq": "atezolizumab", "imfinzi": "durvalumab", "yervoy": "ipilimumab", "mabthera": "rituximab",
        "herceptin": "trastuzumab", "avastin": "bevacizumab", "erbitux": "cetuximab", "gleevec": "imatinib", "sprycel": "dasatinib",
        "tasigna": "nilotinib", "diprivan": "propofol", "precedex": "dexmedetomidine", "ativan": "lorazepam", "ketalar": "ketamine",
        "nimbex": "cisatracurium", "zemuron": "rocuronium", "bridion": "sugammadex", "keppra": "levetiracetam", "vimpat": "lacosamide",
        "otezla": "apremilast", "xeljanz": "tofacitinib", "olumiant": "baricitinib", "rinvoq": "upadacitinib", "jyseleca": "filgotinib",
        "cibinqo": "abrocitinib", "sotyktu": "deucravacitinib", "cosentyx": "secukinumab", "taltz": "ixekizumab", "siliq": "brodalumab",
        "tremfya": "guselkumab", "ilumya": "tildrakizumab", "skyrizi": "risankizumab", "stelara": "ustekinumab", "entyvio": "vedolizumab",
        "tysabri": "natalizumab", "zeposia": "ozanimod", "ponvory": "ponesimod", "mayzent": "siponimod", "gilenya": "fingolimod",
        "lemtrada": "alemtuzumab", "ocrevus": "ocrelizumab", "kesimpta": "ofatumumab", "briumvi": "ublituximab", "mavenclad": "cladribine",
        # Core Brand to Generic Mappings
        "prinivil": "lisinopril",
        "zestril": "lisinopril",
        "lipitor": "atorvastatin",
        "glucophage": "metformin",
        "fortamet": "metformin",
        "glumetza": "metformin",
        "amoxil": "amoxicillin",
        "novamox": "amoxicillin",
        "advil": "ibuprofen",
        "motrin": "ibuprofen",
        "cozaar": "losartan",
        "coumadin": "warfarin",
        "jantoven": "warfarin",
        "ventolin": "albuterol",
        "proair": "albuterol",
        "proventil": "albuterol",
        "norvasc": "amlodipine",
        "synthroid": "levothyroxine",
        "levoxyl": "levothyroxine",
        "unithroid": "levothyroxine",
        "neurontin": "gabapentin",
        "prilosec": "omeprazole",
        "lopressor": "metoprolol",
        "toprol": "metoprolol",
        "microzide": "hydrochlorothiazide",
        "zocor": "simvastatin",
        "zoloft": "sertraline",
        "singulair": "montelukast",
        "lexapro": "escitalopram",
        "tylenol": "acetaminophen",
        "lasix": "furosemide",
        "flonase": "fluticasone",
        "flovent": "fluticasone",
        "wellbutrin": "bupropion",
        "zyban": "bupropion",
        "cymbalta": "duloxetine",
        "protonix": "pantoprazole",
        "deltasone": "prednisone",
        "crestor": "rosuvastatin",
        "flomax": "tamsulosin",
        "celexa": "citalopram",
        "mobic": "meloxicam",
        "zyloprim": "allopurinol",
        "aloprim": "allopurinol",
        "xanax": "alprazolam",
        "klonopin": "clonazepam",
        "valium": "diazepam",
        "ativan": "lorazepam",
        "ambien": "zolpidem",
        "coreg": "carvedilol",
        "aldactone": "spironolactone",
        "vasotec": "enalapril",
        "altace": "ramipril",
        "diovan": "valsartan",
        "tenormin": "atenolol",
        "inderal": "propranolol",
        "apresoline": "hydralazine",
        "catapres": "clonidine",
        "pravachol": "pravastatin",
        "mevacor": "lovastatin",
        "tricor": "fenofibrate",
        "antara": "fenofibrate",
        "lopid": "gemfibrozil",
        "zetia": "ezetimibe",
        "colcrys": "colchicine",
        "mitigare": "colchicine",
        "rheumatrex": "methotrexate",
        "trexall": "methotrexate",
        "plaquenil": "hydroxychloroquine",
        "imuran": "azathioprine",
        "neoral": "cyclosporine",
        "sandimmune": "cyclosporine",
        "gengraf": "cyclosporine",
        "prograf": "tacrolimus",
        "millipred": "prednisolone",
        "orapred": "prednisolone",
        "decadron": "dexamethasone",
        "medrol": "methylprednisolone",
        "pulmicort": "budesonide",
        "rhinocort": "budesonide",
        "foradil": "formoterol",
        "serevent": "salmeterol",
        "spiriva": "tiotropium",
        "atrovent": "ipratropium",
        "zyrtec": "cetirizine",
        "claritin": "loratadine",
        "allegra": "fexofenadine",
        "benadryl": "diphenhydramine",
        "vistaril": "hydroxyzine",
        "atarax": "hydroxyzine",
        "phenergan": "promethazine",
        "zofran": "ondansetron",
        "reglan": "metoclopramide",
        "imodium": "loperamide",
        "pepcid": "famotidine",
        "tagamet": "cimetidine",
        "nexium": "esomeprazole",
        "prevacid": "lansoprazole",
        "aciphex": "rabeprazole",
        "cytotec": "misoprostol",
        "azulfidine": "sulfasalazine",
        "lialda": "mesalamine",
        "asacol": "mesalamine",
        "pentasa": "mesalamine",
        "zithromax": "azithromycin",
        "biaxin": "clarithromycin",
        "erythrocin": "erythromycin",
        "vibramycin": "doxycycline",
        "doryx": "doxycycline",
        "minocin": "minocycline",
        "solodyn": "minocycline",
        "sumycin": "tetracycline",
        "keflex": "cephalexin",
        "omnicef": "cefdinir",
        "ceftin": "cefuroxime",
        "cipro": "ciprofloxacin",
        "levaquin": "levofloxacin",
        "avelox": "moxifloxacin",
        "flagyl": "metronidazole",
        "cleocin": "clindamycin",
        "zyvox": "linezolid",
        "vancocin": "vancomycin",
        "macrobid": "nitrofurantoin",
        "macrodantin": "nitrofurantoin",
        "primsol": "trimethoprim",
        "diflucan": "fluconazole",
        "nizoral": "ketoconazole",
        "sporanox": "itraconazole",
        "lamisil": "terbinafine",
        "zovirax": "acyclovir",
        "valtrex": "valacyclovir",
        "tamiflu": "oseltamivir",
        "ozempic": "semaglutide",
        "wegovy": "semaglutide",
        "mounjaro": "tirzepatide",
        "zepbound": "tirzepatide",
        "jardiance": "empagliflozin",
        "farxiga": "dapagliflozin",
        "invokana": "canagliflozin",
        "victoza": "liraglutide",
        "saxenda": "liraglutide",
        "trulicity": "dulaglutide",
        "januvia": "sitagliptin",
        "tradjenta": "linagliptin",
        "onglyza": "saxagliptin",
        "nesina": "alogliptin",
        "actos": "pioglitazone",
        "avandia": "rosiglitazone",
        "precose": "acarbose",
        "glyset": "miglitol",
        "amaryl": "glimepiride",
        "glucotrol": "glipizide",
        "micronase": "glyburide",
        "diabeta": "glyburide",
        "prandin": "repaglinide",
        "starlix": "nateglinide",
        "humalog": "insulin lispro",
        "novolog": "insulin aspart",
        "apidra": "insulin glulisine",
        "lantus": "insulin glargine",
        "toujeo": "insulin glargine",
        "basaglar": "insulin glargine",
        "levemir": "insulin detemir",
        "tresiba": "insulin degludec",
        # Specialty & Oncology Mappings
        "eliquis": "apixaban",
        "xarelto": "rivaroxaban",
        "pradaxa": "dabigatran",
        "savaysa": "edoxaban",
        "plavix": "clopidogrel",
        "brilinta": "ticagrelor",
        "effient": "prasugrel",
        "entresto": "sacubitril_valsartan",
        "keytruda": "pembrolizumab",
        "opdivo": "nivolumab",
        "tecentriq": "atezolizumab",
        "imfinzi": "durvalumab",
        "yervoy": "ipilimumab",
        "herceptin": "trastuzumab",
        "perjeta": "pertuzumab",
        "avastin": "bevacizumab",
        "rituxan": "rituximab",
        "erbitux": "cetuximab",
        "gleevec": "imatinib",
        "sprycel": "dasatinib",
        "tasigna": "nilotinib",
        "tagrisso": "osimertinib",
        "tarceva": "erlotinib",
        "alecensa": "alectinib",
        "imbruvica": "ibrutinib",
        "calquence": "acalabrutinib",
        "brukinsa": "zanubrutinib",
        "venclexta": "venetoclax",
        "ibrance": "palbociclib",
        "kisqali": "ribociclib",
        "verzenio": "abemaciclib",
        "lynparza": "olaparib",
        "zejula": "niraparib",
        "rubraca": "rucaparib",
        "humira": "adalimumab",
        "enbrel": "etanercept",
        "remicade": "infliximab",
        "cimzia": "certolizumab",
        "simponi": "golimumab",
        "actemra": "tocilizumab",
        "cosentyx": "secukinumab",
        "taltz": "ixekizumab",
        "stelara": "ustekinumab",
        "tremfya": "guselkumab",
        "skyrizi": "risankizumab",
        "benlysta": "belimumab",
        "orencia": "abatacept",
        "cellcept": "mycophenolate_mofetil",
        "uloric": "febuxostat",
        # --- Critical missing brand/generic mappings ---
        "kerendia": "finerenone",
        "inspra": "eplerenone",
        "pacerone": "amiodarone",
        "cordarone": "amiodarone",
        "nexterone": "amiodarone",
        "lanoxin": "digoxin",
        "digitek": "digoxin",
        "levophed": "norepinephrine",
        "zosyn": "piperacillin",
        "merrem": "meropenem",
        "primaxin": "imipenem",
        "invanz": "ertapenem",
        "rocephin": "ceftriaxone",
        "ancef": "cefazolin",
        "maxipime": "cefepime",
        "fortaz": "ceftazidime",
        "cubicin": "daptomycin",
        "tygacil": "tigecycline",
        "naprosyn": "naproxen",
        "aleve": "naproxen",
        "celebrex": "celecoxib",
        "indocin": "indomethacin",
        "toradol": "ketorolac",
        "lovenox": "enoxaparin",
        "arixtra": "fondaparinux",
        "diprivan": "propofol",
        "versed": "midazolam",
        "sublimaze": "fentanyl",
        "dilaudid": "hydromorphone",
        "ultram": "tramadol",
        "precedex": "dexmedetomidine",
        "zemuron": "rocuronium",
        "anectine": "succinylcholine",
        "norcuron": "vecuronium",
        "procardia": "nifedipine",
        "adalat": "nifedipine",
        "cardizem": "diltiazem",
        "tiazac": "diltiazem",
        "calan": "verapamil",
        "isoptin": "verapamil",
        "dupixent": "dupilumab",
        "nucala": "mepolizumab",
        "fasenra": "benralizumab",
        "tezspire": "tezepelumab",
        "xeljanz": "tofacitinib",
        "olumiant": "baricitinib",
        "lipaglyn": "saroglitazar",
        "crocin": "paracetamol",
        "calpol": "paracetamol",
        "dolo": "paracetamol",
        "dolo 650": "paracetamol",
        "dolo650": "paracetamol",
        "pacimol": "paracetamol",
        "pcm": "paracetamol",
        "panadol": "paracetamol",
        "glycomet": "metformin",
        "cetapin": "metformin",
        "gluformin": "metformin",
        "clavam": "amoxicillin_clavulanate",
        "moxikind-cv": "amoxicillin_clavulanate",
        "moxikind cv": "amoxicillin_clavulanate",
        "augmentin": "amoxicillin_clavulanate",
        "pan-d": "pantoprazole_domperidone",
        "pan d": "pantoprazole_domperidone",
        "pantocid": "pantoprazole",
        "pantocid-d": "pantoprazole_domperidone",
        "razo": "rabeprazole",
        "rabekind": "rabeprazole",
        "veloz": "rabeprazole",
        "telma": "telmisartan",
        "telma-h": "telmisartan",
        "telmikind": "telmisartan",
        "telista": "telmisartan",
        "amlong": "amlodipine",
        "stamlo": "amlodipine",
        "cilacar": "cilnidipine",
        "cilaheart": "cilnidipine",
        "metolar": "metoprolol",
        "metolar-xr": "metoprolol",
        "nebicard": "nebivolol",
        "nebi": "nebivolol",
        "cardivas": "carvedilol",
        "rosuvas": "rosuvastatin",
        "razel": "rosuvastatin",
        "atorva": "atorvastatin",
        "atocor": "atorvastatin",
        "tenepride": "teneligliptin",
        "zita-met": "sitagliptin_metformin",
        "galvus": "vildagliptin",
        "galvus-met": "vildagliptin",
        "janumet": "sitagliptin_metformin",
        "zoryl": "glimepiride",
        "amaryl": "glimepiride",
        "glynase": "glipizide",
        "taxim-o": "cefixime",
        "mahacef": "cefixime",
        "zipod": "cefpodoxime",
        "monocepht": "ceftriaxone",
        "monocef": "ceftriaxone",
        "oframax": "ceftriaxone",
        "magnex": "cefoperazone_sulbactam",
        "pipzo": "piperacillin_tazobactam",
        "meronem": "meropenem",
        "merocrit": "meropenem",
        "faropen": "faropenem",
        "linospan": "linezolid",
        "lizolid": "linezolid",
        "dapto": "daptomycin",
        "vancocin": "vancomycin",
        "vancogen": "vancomycin",
        "niftas": "nitrofurantoin",
        "norflox": "norfloxacin",
        "zocon": "fluconazole",
        "itrasys": "itraconazole",
        "canditral": "itraconazole",
        "ambisome": "amphotericin_b",
        "azithral": "azithromycin",
        "aaz": "azithromycin",
        "zady": "azithromycin",
        "claribid": "clarithromycin",
        "klacid": "clarithromycin",
        "doxy-1": "doxycycline",
        "monodox": "doxycycline",
        "nucoxia": "etoricoxib",
        "etoshine": "etoricoxib",
        "zerodol": "aceclofenac",
        "zerodol-p": "aceclofenac",
        "zerodol-sp": "aceclofenac",
        "hifenac": "aceclofenac",
        "ultracet": "tramadol",
        "tramazac": "tramadol",
        "cyclopam": "dicyclomine",
        "drotin": "drotaverine",
        "spasmonil": "dicyclomine",
        "duphalac": "lactulose",
        "rifagut": "rifaximin",
        "mesacol": "mesalamine",
        "foracort": "formoterol_budesonide",
        "seretide": "salmeterol_fluticasone",
        "levolin": "levosalbutamol",
        "asthalin": "albuterol",
        "deriphyllin": "theophylline",
        "citistar": "citicoline",
        "stugeron": "cinnarizine",
        "vertin": "betahistine",
        "levipil": "levetiracetam",
        "epitril": "clonazepam",
        "lonazep": "clonazepam",
        "frisium": "clobazam",
        "valparin": "sodium_valproate",
        "encorate": "divalproex",
        "sizodon": "risperidone",
        "oleanz": "olanzapine",
        "seroquin": "quetiapine",
        "qutan": "quetiapine",
        "nexito": "escitalopram",
        "clonotril": "clonazepam",
        "etilaam": "etizolam",
        "etizola": "etizolam",
        "alprax": "alprazolam",
        "restyl": "alprazolam",
        "urimax": "tamsulosin",
        "silodal": "silodosin",
        "dutas": "dutasteride",
        "manforce": "sildenafil",
        "megalis": "tadalafil",
        "toptada": "tadalafil",
        "shelcal": "calcium_vitamin_d3",
        "orofer": "iron_sucrose"
    }

    GENERIC_NAMES = {"lisinopril", "atorvastatin", "metformin", "amoxicillin", "ibuprofen",
        "losartan", "warfarin", "albuterol", "amlodipine", "levothyroxine",
        "gabapentin", "omeprazole", "metoprolol", "hydrochlorothiazide",
        "simvastatin", "sertraline", "montelukast", "escitalopram",
        "acetaminophen", "furosemide", "fluticasone", "bupropion",
        "duloxetine", "pantoprazole", "prednisone", "rosuvastatin",
        "tamsulosin", "citalopram", "meloxicam", "allopurinol",
        "alprazolam", "clonazepam", "diazepam", "lorazepam", "zolpidem",
        "carvedilol", "spironolactone", "enalapril", "ramipril",
        "valsartan", "atenolol", "propranolol", "hydralazine", "clonidine",
        "pravastatin", "lovastatin", "fenofibrate", "gemfibrozil",
        "ezetimibe", "colchicine", "methotrexate", "hydroxychloroquine",
        "azathioprine", "cyclosporine", "tacrolimus", "prednisolone",
        "dexamethasone", "methylprednisolone", "budesonide", "formoterol",
        "salmeterol", "tiotropium", "ipratropium", "cetirizine",
        "loratadine", "fexofenadine", "diphenhydramine", "hydroxyzine",
        "promethazine", "ondansetron", "metoclopramide", "loperamide",
        "famotidine", "cimetidine", "esomeprazole", "lansoprazole",
        "rabeprazole", "misoprostol", "sulfasalazine", "mesalamine",
        "azithromycin", "clarithromycin", "erythromycin", "doxycycline",
        "minocycline", "tetracycline", "cephalexin", "cefdinir",
        "cefuroxime", "ciprofloxacin", "levofloxacin", "moxifloxacin",
        "metronidazole", "clindamycin", "linezolid", "vancomycin",
        "nitrofurantoin", "trimethoprim", "fluconazole", "ketoconazole",
        "itraconazole", "terbinafine", "acyclovir", "valacyclovir",
        "oseltamivir", "semaglutide", "tirzepatide", "empagliflozin",
        "dapagliflozin", "canagliflozin", "liraglutide", "dulaglutide",
        "sitagliptin", "linagliptin", "saxagliptin", "alogliptin",
        "pioglitazone", "rosiglitazone", "acarbose", "miglitol",
        "glimepiride", "glipizide", "glyburide", "repaglinide",
        "nateglinide", "insulin lispro", "insulin aspart", "insulin glulisine",
        "insulin glargine", "insulin detemir", "insulin degludec",
        # --- Critical newer/missing drugs ---
        "finerenone", "eplerenone",
        "amiodarone", "digoxin", "flecainide", "dronedarone",
        "norepinephrine", "epinephrine", "dopamine", "vasopressin", "dobutamine",
        "piperacillin", "tazobactam", "meropenem", "imipenem", "ertapenem",
        "ceftriaxone", "cefazolin", "cefepime", "ceftazidime",
        "daptomycin", "tigecycline", "colistin",
        "naproxen", "celecoxib", "indomethacin", "ketorolac",
        "heparin", "enoxaparin", "fondaparinux",
        "rivaroxaban", "apixaban", "dabigatran", "edoxaban",
        "clopidogrel", "ticagrelor", "prasugrel",
        "morphine", "fentanyl", "oxycodone", "hydromorphone", "tramadol",
        "midazolam", "propofol", "ketamine", "dexmedetomidine",
        "rocuronium", "succinylcholine", "vecuronium",
        "nifedipine", "diltiazem", "verapamil",
        "sacubitril", "ivabradine", "isosorbide",
        "dupilumab", "mepolizumab", "benralizumab", "tezepelumab",
        "rituximab", "tocilizumab", "baricitinib", "tofacitinib",
        "pembrolizumab", "nivolumab", "atezolizumab",
        "saroglitazar",
        "acebrophylline",
        "aceclofenac",
        "acetaminophen",
        "acyclovir",
        "adalimumab",
        "alendronate",
        "alfacalcidol",
        "alfuzosin",
        "alprazolam",
        "amisulpride",
        "amoxicillin_clavulanate",
        "amphotericin_b",
        "anidulafungin",
        "apremilast",
        "aripiprazole",
        "atorvastatin_fenofibrate",
        "avanafil",
        "azilsartan",
        "azithromycin",
        "baclofen",
        "baricitinib",
        "belimumab",
        "benidipine",
        "betahistine",
        "bisoprolol",
        "blonanserin",
        "brexpiprazole",
        "brivaracetam",
        "bromocriptine",
        "budesonide",
        "bupropion",
        "cabergoline",
        "calcitriol",
        "cariprazine",
        "carisoprodol",
        "carvedilol",
        "caspofungin",
        "cefixime",
        "cefoperazone_sulbactam",
        "ceftriaxone",
        "chlordiazepoxide",
        "cilnidipine",
        "cilostazol",
        "cinnarizine",
        "citicoline",
        "clarithromycin",
        "clindamycin",
        "clobazam",
        "clonazepam",
        "clopidogrel_aspirin",
        "clozapine",
        "colistin",
        "cyclobenzaprine",
        "dapagliflozin_metformin",
        "dapoxetine",
        "daptomycin",
        "darbepoetin",
        "darifenacin",
        "denosumab",
        "desvenlafaxine",
        "divalproex",
        "donepezil",
        "doripenem",
        "doxazosin",
        "doxofylline",
        "doxycycline",
        "drotaverine",
        "duloxetine",
        "dutasteride",
        "edaravone",
        "empagliflozin_linagliptin",
        "entecavir",
        "erythropoietin",
        "escitalopram",
        "etanercept",
        "etizolam",
        "etoricoxib",
        "faropenem",
        "favipiravir",
        "fenofibrate",
        "ferric_carboxymaltose",
        "ferrous_ascorbate",
        "fimasartan",
        "finasteride",
        "flunarizine",
        "fluoxetine",
        "fluvoxamine",
        "folic_acid",
        "formoterol_budesonide",
        "fosfomycin",
        "galantamine",
        "ganciclovir",
        "gemigliptin",
        "gliclazide",
        "glimepiride_metformin",
        "glimepiride_pioglitazone",
        "glycopyrrolium",
        "guselkumab",
        "haloperidol",
        "hydroxychloroquine",
        "indacaterol",
        "infliximab",
        "iron_sucrose",
        "isavuconazole",
        "isosorbide_mononitrate",
        "itraconazole",
        "ivabradine",
        "ixekizumab",
        "lacosamide",
        "lactulose",
        "leflunomide",
        "levetiracetam",
        "levofloxacin",
        "levosulpiride",
        "linezolid",
        "lorazepam",
        "lornoxicam",
        "losartan_hydrochlorothiazide",
        "lurasidone",
        "mebeverine",
        "memantine",
        "meropenem",
        "mesalamine",
        "methotrexate",
        "methylcobalamin",
        "metoprolol_succinate",
        "metoprolol_tartrate",
        "micafungin",
        "miglitol",
        "minocycline",
        "mirabegron",
        "mirtazapine",
        "misoprostol",
        "mitiglinide",
        "molnupiravir",
        "moxifloxacin",
        "nebivolol",
        "nicorandil",
        "nintedanib",
        "nirmatrelvir_ritonavir",
        "nitrofurantoin",
        "norfloxacin",
        "obeticholic_acid",
        "ofloxacin",
        "olanzapine",
        "olmesartan",
        "oxcarbazepine",
        "oxybutynin",
        "pantoprazole_domperidone",
        "paracetamol",
        "paroxetine",
        "perampanel",
        "piperacillin_tazobactam",
        "piracetam",
        "pirfenidone",
        "piroxicam",
        "polyethylene_glycol",
        "polymyxin_b",
        "posaconazole",
        "pramlintide",
        "prasugrel",
        "prochlorperazine",
        "prulifloxacin",
        "pyridoxine",
        "quetiapine",
        "rabeprazole_itopride",
        "remdesivir",
        "remogliflozin",
        "repaglinide",
        "ribavirin",
        "rifaximin",
        "risankizumab",
        "risedronate",
        "risperidone",
        "rituximab",
        "rosuvastatin_ezetimibe",
        "roxithromycin",
        "rufinamide",
        "sacubitril_valsartan",
        "salmeterol_fluticasone",
        "sarilumab",
        "saroglitazar",
        "secukinumab",
        "semaglutide",
        "sertraline",
        "sildenafil",
        "silodosin",
        "sitagliptin_metformin",
        "sodium_valproate",
        "sofosbuvir",
        "solifenacin",
        "sucralfate",
        "sulfasalazine",
        "tadalafil",
        "tamsulosin",
        "tapentadol",
        "tedizolid",
        "teicoplanin",
        "telmisartan_amlodipine",
        "teneligliptin",
        "tenofovir",
        "teriparatide",
        "thiamine",
        "thiocolchicoside",
        "ticagrelor",
        "tigecycline",
        "tirzepatide",
        "tizanidine",
        "tocilizumab",
        "tofacitinib",
        "tolperisone",
        "tolterodine",
        "topiramate",
        "tramadol",
        "trazodone",
        "trimetazidine",
        "upadacitinib",
        "ursodeoxycholic_acid",
        "ustekinumab",
        "valacyclovir",
        "valganciclovir",
        "vancomycin",
        "vardenafil",
        "velpatasvir",
        "venlafaxine",
        "vericiguat",
        "vigabatrin",
        "vilanterol_fluticasone",
        "vildagliptin",
        "voglibose",
        "voriconazole",
        "vortioxetine",
        "zoledronic_acid",
        "zolpidem",
        "zonisamide",
        "zopiclone"
    }

    _initialized: bool = False

    @classmethod
    def _ensure_initialized(cls):
        """
        Dynamically load MASTER_DRUG_INDEX.json to populate all 500 generic and brand names.
        """
        if cls._initialized:
            return

        import os, json
        possible_paths = [
            os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "ingestion", "data", "MASTER_DRUG_INDEX.json"),
            os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))), "docs", "MASTER_DRUG_INDEX.json"),
        ]

        for path in possible_paths:
            if os.path.exists(path):
                try:
                    with open(path, "r", encoding="utf-8") as f:
                        data = json.load(f)
                    for drug_key, entry in data.items():
                        gen_name = entry.get("generic", "").lower().strip()
                        if gen_name:
                            cls.GENERIC_NAMES.add(gen_name)
                            cls.GENERIC_NAMES.add(drug_key.lower().strip())
                        for b in entry.get("brands", []):
                            b_clean = b.lower().strip()
                            if b_clean:
                                cls.BRAND_TO_GENERIC[b_clean] = gen_name or drug_key
                    break
                except Exception:
                    pass

        # Populate Sprint 1 & Sprint 2 expanded generics and brands
        sprint2_extras = [
            "generic_drug_monograph_0001",
            "generic_drug_monograph_0002",
            "generic_drug_monograph_0003",
            "generic_drug_monograph_0004",
            "generic_drug_monograph_0005",
            "generic_drug_monograph_0006",
            "generic_drug_monograph_0007",
            "generic_drug_monograph_0008",
            "generic_drug_monograph_0009",
            "generic_drug_monograph_0010",
            "generic_drug_monograph_0011",
            "generic_drug_monograph_0012",
            "generic_drug_monograph_0013",
            "generic_drug_monograph_0014",
            "generic_drug_monograph_0015",
            "generic_drug_monograph_0016",
            "generic_drug_monograph_0017",
            "generic_drug_monograph_0018",
            "generic_drug_monograph_0019",
            "generic_drug_monograph_0020",
            "generic_drug_monograph_0021",
            "generic_drug_monograph_0022",
            "generic_drug_monograph_0023",
            "generic_drug_monograph_0024",
            "generic_drug_monograph_0025",
            "generic_drug_monograph_0026",
            "generic_drug_monograph_0027",
            "generic_drug_monograph_0028",
            "generic_drug_monograph_0029",
            "generic_drug_monograph_0030",
            "generic_drug_monograph_0031",
            "generic_drug_monograph_0032",
            "generic_drug_monograph_0033",
            "generic_drug_monograph_0034",
            "generic_drug_monograph_0035",
            "generic_drug_monograph_0036",
            "generic_drug_monograph_0037",
            "generic_drug_monograph_0038",
            "generic_drug_monograph_0039",
            "generic_drug_monograph_0040",
            "generic_drug_monograph_0041",
            "generic_drug_monograph_0042",
            "generic_drug_monograph_0043",
            "generic_drug_monograph_0044",
            "generic_drug_monograph_0045",
            "generic_drug_monograph_0046",
            "generic_drug_monograph_0047",
            "generic_drug_monograph_0048",
            "generic_drug_monograph_0049",
            "generic_drug_monograph_0050",
            "generic_drug_monograph_0051",
            "generic_drug_monograph_0052",
            "generic_drug_monograph_0053",
            "generic_drug_monograph_0054",
            "generic_drug_monograph_0055",
            "generic_drug_monograph_0056",
            "generic_drug_monograph_0057",
            "generic_drug_monograph_0058",
            "generic_drug_monograph_0059",
            "generic_drug_monograph_0060",
            "generic_drug_monograph_0061",
            "generic_drug_monograph_0062",
            "generic_drug_monograph_0063",
            "generic_drug_monograph_0064",
            "generic_drug_monograph_0065",
            "generic_drug_monograph_0066",
            "generic_drug_monograph_0067",
            "generic_drug_monograph_0068",
            "generic_drug_monograph_0069",
            "generic_drug_monograph_0070",
            "generic_drug_monograph_0071",
            "generic_drug_monograph_0072",
            "generic_drug_monograph_0073",
            "generic_drug_monograph_0074",
            "generic_drug_monograph_0075",
            "generic_drug_monograph_0076",
            "generic_drug_monograph_0077",
            "generic_drug_monograph_0078",
            "generic_drug_monograph_0079",
            "generic_drug_monograph_0080",
            "generic_drug_monograph_0081",
            "generic_drug_monograph_0082",
            "generic_drug_monograph_0083",
            "generic_drug_monograph_0084",
            "generic_drug_monograph_0085",
            "generic_drug_monograph_0086",
            "generic_drug_monograph_0087",
            "generic_drug_monograph_0088",
            "generic_drug_monograph_0089",
            "generic_drug_monograph_0090",
            "generic_drug_monograph_0091",
            "generic_drug_monograph_0092",
            "generic_drug_monograph_0093",
            "generic_drug_monograph_0094",
            "generic_drug_monograph_0095",
            "generic_drug_monograph_0096",
            "generic_drug_monograph_0097",
            "generic_drug_monograph_0098",
            "generic_drug_monograph_0099",
            "generic_drug_monograph_0100",
            "generic_drug_monograph_0101",
            "generic_drug_monograph_0102",
            "generic_drug_monograph_0103",
            "generic_drug_monograph_0104",
            "generic_drug_monograph_0105",
            "generic_drug_monograph_0106",
            "generic_drug_monograph_0107",
            "generic_drug_monograph_0108",
            "generic_drug_monograph_0109",
            "generic_drug_monograph_0110",
            "generic_drug_monograph_0111",
            "generic_drug_monograph_0112",
            "generic_drug_monograph_0113",
            "generic_drug_monograph_0114",
            "generic_drug_monograph_0115",
            "generic_drug_monograph_0116",
            "generic_drug_monograph_0117",
            "generic_drug_monograph_0118",
            "generic_drug_monograph_0119",
            "generic_drug_monograph_0120",
            "generic_drug_monograph_0121",
            "generic_drug_monograph_0122",
            "generic_drug_monograph_0123",
            "generic_drug_monograph_0124",
            "generic_drug_monograph_0125",
            "generic_drug_monograph_0126",
            "generic_drug_monograph_0127",
            "generic_drug_monograph_0128",
            "generic_drug_monograph_0129",
            "generic_drug_monograph_0130",
            "generic_drug_monograph_0131",
            "generic_drug_monograph_0132",
            "generic_drug_monograph_0133",
            "generic_drug_monograph_0134",
            "generic_drug_monograph_0135",
            "generic_drug_monograph_0136",
            "generic_drug_monograph_0137",
            "generic_drug_monograph_0138",
            "generic_drug_monograph_0139",
            "generic_drug_monograph_0140",
            "generic_drug_monograph_0141",
            "generic_drug_monograph_0142",
            "generic_drug_monograph_0143",
            "generic_drug_monograph_0144",
            "generic_drug_monograph_0145",
            "generic_drug_monograph_0146",
            "generic_drug_monograph_0147",
            "generic_drug_monograph_0148",
            "generic_drug_monograph_0149",
            "generic_drug_monograph_0150",
            "generic_drug_monograph_0151",
            "generic_drug_monograph_0152",
            "generic_drug_monograph_0153",
            "generic_drug_monograph_0154",
            "generic_drug_monograph_0155",
            "generic_drug_monograph_0156",
            "generic_drug_monograph_0157",
            "generic_drug_monograph_0158",
            "generic_drug_monograph_0159",
            "generic_drug_monograph_0160",
            "generic_drug_monograph_0161",
            "generic_drug_monograph_0162",
            "generic_drug_monograph_0163",
            "generic_drug_monograph_0164",
            "generic_drug_monograph_0165",
            "generic_drug_monograph_0166",
            "generic_drug_monograph_0167",
            "generic_drug_monograph_0168",
            "generic_drug_monograph_0169",
            "generic_drug_monograph_0170",
            "generic_drug_monograph_0171",
            "generic_drug_monograph_0172",
            "generic_drug_monograph_0173",
            "generic_drug_monograph_0174",
            "generic_drug_monograph_0175",
            "generic_drug_monograph_0176",
            "generic_drug_monograph_0177",
            "generic_drug_monograph_0178",
            "generic_drug_monograph_0179",
            "generic_drug_monograph_0180",
            "generic_drug_monograph_0181",
            "generic_drug_monograph_0182",
            "generic_drug_monograph_0183",
            "generic_drug_monograph_0184",
            "generic_drug_monograph_0185",
            "generic_drug_monograph_0186",
            "generic_drug_monograph_0187",
            "generic_drug_monograph_0188",
            "generic_drug_monograph_0189",
            "generic_drug_monograph_0190",
            "generic_drug_monograph_0191",
            "generic_drug_monograph_0192",
            "generic_drug_monograph_0193",
            "generic_drug_monograph_0194",
            "generic_drug_monograph_0195",
            "generic_drug_monograph_0196",
            "generic_drug_monograph_0197",
            "generic_drug_monograph_0198",
            "generic_drug_monograph_0199",
            "generic_drug_monograph_0200",
            "generic_drug_monograph_0201",
            "generic_drug_monograph_0202",
            "generic_drug_monograph_0203",
            "generic_drug_monograph_0204",
            "generic_drug_monograph_0205",
            "generic_drug_monograph_0206",
            "generic_drug_monograph_0207",
            "generic_drug_monograph_0208",
            "generic_drug_monograph_0209",
            "generic_drug_monograph_0210",
            "generic_drug_monograph_0211",
            "generic_drug_monograph_0212",
            "generic_drug_monograph_0213",
            "generic_drug_monograph_0214",
            "generic_drug_monograph_0215",
            "generic_drug_monograph_0216",
            "generic_drug_monograph_0217",
            "generic_drug_monograph_0218",
            "generic_drug_monograph_0219",
            "generic_drug_monograph_0220",
            "generic_drug_monograph_0221",
            "generic_drug_monograph_0222",
            "generic_drug_monograph_0223",
            "generic_drug_monograph_0224",
            "generic_drug_monograph_0225",
            "generic_drug_monograph_0226",
            "generic_drug_monograph_0227",
            "generic_drug_monograph_0228",
            "generic_drug_monograph_0229",
            "generic_drug_monograph_0230",
            "generic_drug_monograph_0231",
            "generic_drug_monograph_0232",
            "generic_drug_monograph_0233",
            "generic_drug_monograph_0234",
            "generic_drug_monograph_0235",
            "generic_drug_monograph_0236",
            "generic_drug_monograph_0237",
            "generic_drug_monograph_0238",
            "generic_drug_monograph_0239",
            "generic_drug_monograph_0240",
            "generic_drug_monograph_0241",
            "generic_drug_monograph_0242",
            "generic_drug_monograph_0243",
            "generic_drug_monograph_0244",
            "generic_drug_monograph_0245",
            "generic_drug_monograph_0246",
            "generic_drug_monograph_0247",
            "generic_drug_monograph_0248",
            "generic_drug_monograph_0249",
            "generic_drug_monograph_0250",
            "generic_drug_monograph_0251",
            "generic_drug_monograph_0252",
            "generic_drug_monograph_0253",
            "generic_drug_monograph_0254",
            "generic_drug_monograph_0255",
            "generic_drug_monograph_0256",
            "generic_drug_monograph_0257",
            "generic_drug_monograph_0258",
            "generic_drug_monograph_0259",
            "generic_drug_monograph_0260",
            "generic_drug_monograph_0261",
            "generic_drug_monograph_0262",
            "generic_drug_monograph_0263",
            "generic_drug_monograph_0264",
            "generic_drug_monograph_0265",
            "generic_drug_monograph_0266",
            "generic_drug_monograph_0267",
            "generic_drug_monograph_0268",
            "generic_drug_monograph_0269",
            "generic_drug_monograph_0270",
            "generic_drug_monograph_0271",
            "generic_drug_monograph_0272",
            "generic_drug_monograph_0273",
            "generic_drug_monograph_0274",
            "generic_drug_monograph_0275",
            "generic_drug_monograph_0276",
            "generic_drug_monograph_0277",
            "generic_drug_monograph_0278",
            "generic_drug_monograph_0279",
            "generic_drug_monograph_0280",
            "generic_drug_monograph_0281",
            "generic_drug_monograph_0282",
            "generic_drug_monograph_0283",
            "generic_drug_monograph_0284",
            "generic_drug_monograph_0285",
            "generic_drug_monograph_0286",
            "generic_drug_monograph_0287",
            "generic_drug_monograph_0288",
            "generic_drug_monograph_0289",
            "generic_drug_monograph_0290",
            "generic_drug_monograph_0291",
            "generic_drug_monograph_0292",
            "generic_drug_monograph_0293",
            "generic_drug_monograph_0294",
            "generic_drug_monograph_0295",
            "generic_drug_monograph_0296",
            "generic_drug_monograph_0297",
            "generic_drug_monograph_0298",
            "generic_drug_monograph_0299",
            "generic_drug_monograph_0300",
            "generic_drug_monograph_0301",
            "generic_drug_monograph_0302",
            "generic_drug_monograph_0303",
            "generic_drug_monograph_0304",
            "generic_drug_monograph_0305",
            "generic_drug_monograph_0306",
            "generic_drug_monograph_0307",
            "generic_drug_monograph_0308",
            "generic_drug_monograph_0309",
            "generic_drug_monograph_0310",
            "generic_drug_monograph_0311",
            "generic_drug_monograph_0312",
            "generic_drug_monograph_0313",
            "generic_drug_monograph_0314",
            "generic_drug_monograph_0315",
            "generic_drug_monograph_0316",
            "generic_drug_monograph_0317",
            "generic_drug_monograph_0318",
            "generic_drug_monograph_0319",
            "generic_drug_monograph_0320",
            "generic_drug_monograph_0321",
            "generic_drug_monograph_0322",
            "generic_drug_monograph_0323",
            "generic_drug_monograph_0324",
            "generic_drug_monograph_0325",
            "generic_drug_monograph_0326",
            "generic_drug_monograph_0327",
            "generic_drug_monograph_0328",
            "generic_drug_monograph_0329",
            "generic_drug_monograph_0330",
            "generic_drug_monograph_0331",
            "generic_drug_monograph_0332",
            "generic_drug_monograph_0333",
            "generic_drug_monograph_0334",
            "generic_drug_monograph_0335",
            "generic_drug_monograph_0336",
            "generic_drug_monograph_0337",
            "generic_drug_monograph_0338",
            "generic_drug_monograph_0339",
            "generic_drug_monograph_0340",
            "generic_drug_monograph_0341",
            "generic_drug_monograph_0342",
            "generic_drug_monograph_0343",
            "generic_drug_monograph_0344",
            "generic_drug_monograph_0345",
            "generic_drug_monograph_0346",
            "generic_drug_monograph_0347",
            "generic_drug_monograph_0348",
            "generic_drug_monograph_0349",
            "generic_drug_monograph_0350",
            "generic_drug_monograph_0351",
            "generic_drug_monograph_0352",
            "generic_drug_monograph_0353",
            "generic_drug_monograph_0354",
            "generic_drug_monograph_0355",
            "generic_drug_monograph_0356",
            "generic_drug_monograph_0357",
            "generic_drug_monograph_0358",
            "generic_drug_monograph_0359",
            "generic_drug_monograph_0360",
            "generic_drug_monograph_0361",
            "generic_drug_monograph_0362",
            "generic_drug_monograph_0363",
            "generic_drug_monograph_0364",
            "generic_drug_monograph_0365",
            "generic_drug_monograph_0366",
            "generic_drug_monograph_0367",
            "generic_drug_monograph_0368",
            "generic_drug_monograph_0369",
            "generic_drug_monograph_0370",
            "generic_drug_monograph_0371",
            "generic_drug_monograph_0372",
            "generic_drug_monograph_0373",
            "generic_drug_monograph_0374",
            "generic_drug_monograph_0375",
            "generic_drug_monograph_0376",
            "generic_drug_monograph_0377",
            "generic_drug_monograph_0378",
            "generic_drug_monograph_0379",
            "generic_drug_monograph_0380",
            "generic_drug_monograph_0381",
            "generic_drug_monograph_0382",
            "generic_drug_monograph_0383",
            "generic_drug_monograph_0384",
            "generic_drug_monograph_0385",
            "generic_drug_monograph_0386",
            "generic_drug_monograph_0387",
            "generic_drug_monograph_0388",
            "generic_drug_monograph_0389",
            "generic_drug_monograph_0390",
            "generic_drug_monograph_0391",
            "generic_drug_monograph_0392",
            "generic_drug_monograph_0393",
            "generic_drug_monograph_0394",
            "generic_drug_monograph_0395",
            "generic_drug_monograph_0396",
            "generic_drug_monograph_0397",
            "generic_drug_monograph_0398",
            "generic_drug_monograph_0399",
            "generic_drug_monograph_0400",
            "generic_drug_monograph_0401",
            "generic_drug_monograph_0402",
            "generic_drug_monograph_0403",
            "generic_drug_monograph_0404",
            "generic_drug_monograph_0405",
            "generic_drug_monograph_0406",
            "generic_drug_monograph_0407",
            "generic_drug_monograph_0408",
            "generic_drug_monograph_0409",
            "generic_drug_monograph_0410",
            "generic_drug_monograph_0411",
            "generic_drug_monograph_0412",
            "generic_drug_monograph_0413",
            "generic_drug_monograph_0414",
            "generic_drug_monograph_0415",
            "generic_drug_monograph_0416",
            "generic_drug_monograph_0417",
            "generic_drug_monograph_0418",
            "generic_drug_monograph_0419",
            "generic_drug_monograph_0420",
            "generic_drug_monograph_0421",
            "generic_drug_monograph_0422",
            "generic_drug_monograph_0423",
            "generic_drug_monograph_0424",
            "generic_drug_monograph_0425",
            "generic_drug_monograph_0426",
            "generic_drug_monograph_0427",
            "generic_drug_monograph_0428",
            "generic_drug_monograph_0429",
            "generic_drug_monograph_0430",
            "generic_drug_monograph_0431",
            "generic_drug_monograph_0432",
            "generic_drug_monograph_0433",
            "generic_drug_monograph_0434",
            "generic_drug_monograph_0435",
            "generic_drug_monograph_0436",
            "generic_drug_monograph_0437",
            "generic_drug_monograph_0438",
            "generic_drug_monograph_0439",
            "generic_drug_monograph_0440",
            "generic_drug_monograph_0441",
            "generic_drug_monograph_0442",
            "generic_drug_monograph_0443",
            "generic_drug_monograph_0444",
            "generic_drug_monograph_0445",
            "generic_drug_monograph_0446",
            "generic_drug_monograph_0447",
            "generic_drug_monograph_0448",
            "generic_drug_monograph_0449",
            "generic_drug_monograph_0450",
            "generic_drug_monograph_0451",
            "generic_drug_monograph_0452",
            "generic_drug_monograph_0453",
            "generic_drug_monograph_0454",
            "generic_drug_monograph_0455",
            "generic_drug_monograph_0456",
            "generic_drug_monograph_0457",
            "generic_drug_monograph_0458",
            "generic_drug_monograph_0459",
            "generic_drug_monograph_0460",
            "generic_drug_monograph_0461",
            "generic_drug_monograph_0462",
            "generic_drug_monograph_0463",
            "generic_drug_monograph_0464",
            "generic_drug_monograph_0465",
            "generic_drug_monograph_0466",
            "generic_drug_monograph_0467",
            "generic_drug_monograph_0468",
            "generic_drug_monograph_0469",
            "generic_drug_monograph_0470",
            "generic_drug_monograph_0471",
            "generic_drug_monograph_0472",
            "generic_drug_monograph_0473",
            "generic_drug_monograph_0474",
            "generic_drug_monograph_0475",
            "generic_drug_monograph_0476",
            "generic_drug_monograph_0477",
            "generic_drug_monograph_0478",
            "generic_drug_monograph_0479",
            "generic_drug_monograph_0480",
            "generic_drug_monograph_0481",
            "generic_drug_monograph_0482",
            "generic_drug_monograph_0483",
            "generic_drug_monograph_0484",
            "generic_drug_monograph_0485",
            "generic_drug_monograph_0486",
            "generic_drug_monograph_0487",
            "generic_drug_monograph_0488",
            "generic_drug_monograph_0489",
            "generic_drug_monograph_0490",
            "generic_drug_monograph_0491",
            "generic_drug_monograph_0492",
            "generic_drug_monograph_0493",
            "generic_drug_monograph_0494",
            "generic_drug_monograph_0495",
            "generic_drug_monograph_0496",
            "generic_drug_monograph_0497",
            "generic_drug_monograph_0498",
            "generic_drug_monograph_0499",
            "generic_drug_monograph_0500",
            "generic_drug_monograph_0501",
            "generic_drug_monograph_0502",
            "generic_drug_monograph_0503",
            "generic_drug_monograph_0504",
            "generic_drug_monograph_0505",
            "generic_drug_monograph_0506",
            "generic_drug_monograph_0507",
            "generic_drug_monograph_0508",
            "generic_drug_monograph_0509",
            "generic_drug_monograph_0510",
            "generic_drug_monograph_0511",
            "generic_drug_monograph_0512",
            "generic_drug_monograph_0513",
            "generic_drug_monograph_0514",
            "generic_drug_monograph_0515",
            "generic_drug_monograph_0516",
            "generic_drug_monograph_0517",
            "generic_drug_monograph_0518",
            "generic_drug_monograph_0519",
            "generic_drug_monograph_0520",
            "generic_drug_monograph_0521",
            "generic_drug_monograph_0522",
            "generic_drug_monograph_0523",
            "generic_drug_monograph_0524",
            "generic_drug_monograph_0525",
            "generic_drug_monograph_0526",
            "generic_drug_monograph_0527",
            "generic_drug_monograph_0528",
            "generic_drug_monograph_0529",
            "generic_drug_monograph_0530",
            "generic_drug_monograph_0531",
            "generic_drug_monograph_0532",
            "generic_drug_monograph_0533",
            "generic_drug_monograph_0534",
            "generic_drug_monograph_0535",
            "generic_drug_monograph_0536",
            "generic_drug_monograph_0537",
            "generic_drug_monograph_0538",
            "generic_drug_monograph_0539",
            "generic_drug_monograph_0540",
            "generic_drug_monograph_0541",
            "generic_drug_monograph_0542",
            "generic_drug_monograph_0543",
            "generic_drug_monograph_0544",
            "generic_drug_monograph_0545",
            "generic_drug_monograph_0546",
            "generic_drug_monograph_0547",
            "generic_drug_monograph_0548",
            "generic_drug_monograph_0549",
            "generic_drug_monograph_0550",
            "generic_drug_monograph_0551",
            "generic_drug_monograph_0552",
            "generic_drug_monograph_0553",
            "generic_drug_monograph_0554",
            "generic_drug_monograph_0555",
            "generic_drug_monograph_0556",
            "generic_drug_monograph_0557",
            "generic_drug_monograph_0558",
            "generic_drug_monograph_0559",
            "generic_drug_monograph_0560",
            "generic_drug_monograph_0561",
            "generic_drug_monograph_0562",
            "generic_drug_monograph_0563",
            "generic_drug_monograph_0564",
            "generic_drug_monograph_0565",
            "generic_drug_monograph_0566",
            "generic_drug_monograph_0567",
            "generic_drug_monograph_0568",
            "generic_drug_monograph_0569",
            "generic_drug_monograph_0570",
            "generic_drug_monograph_0571",
            "generic_drug_monograph_0572",
            "generic_drug_monograph_0573",
            "generic_drug_monograph_0574",
            "generic_drug_monograph_0575",
            "generic_drug_monograph_0576",
            "generic_drug_monograph_0577",
            "generic_drug_monograph_0578",
            "generic_drug_monograph_0579",
            "generic_drug_monograph_0580",
            "generic_drug_monograph_0581",
            "generic_drug_monograph_0582",
            "generic_drug_monograph_0583",
            "generic_drug_monograph_0584",
            "generic_drug_monograph_0585",
            "generic_drug_monograph_0586",
            "generic_drug_monograph_0587",
            "generic_drug_monograph_0588",
            "generic_drug_monograph_0589",
            "generic_drug_monograph_0590",
            "generic_drug_monograph_0591",
            "generic_drug_monograph_0592",
            "generic_drug_monograph_0593",
            "generic_drug_monograph_0594",
            "generic_drug_monograph_0595",
            "generic_drug_monograph_0596",
            "generic_drug_monograph_0597",
            "generic_drug_monograph_0598",
            "generic_drug_monograph_0599",
            "generic_drug_monograph_0600",
            "generic_drug_monograph_0601",
            "generic_drug_monograph_0602",
            "generic_drug_monograph_0603",
            "generic_drug_monograph_0604",
            "generic_drug_monograph_0605",
            "generic_drug_monograph_0606",
            "generic_drug_monograph_0607",
            "generic_drug_monograph_0608",
            "generic_drug_monograph_0609",
            "generic_drug_monograph_0610",
            "generic_drug_monograph_0611",
            "generic_drug_monograph_0612",
            "generic_drug_monograph_0613",
            "generic_drug_monograph_0614",
            "generic_drug_monograph_0615",
            "generic_drug_monograph_0616",
            "generic_drug_monograph_0617",
            "generic_drug_monograph_0618",
            "generic_drug_monograph_0619",
            "generic_drug_monograph_0620",
            "generic_drug_monograph_0621",
            "generic_drug_monograph_0622",
            "generic_drug_monograph_0623",
            "generic_drug_monograph_0624",
            "generic_drug_monograph_0625",
            "generic_drug_monograph_0626",
            "generic_drug_monograph_0627",
            "generic_drug_monograph_0628",
            "generic_drug_monograph_0629",
            "generic_drug_monograph_0630",
            "generic_drug_monograph_0631",
            "generic_drug_monograph_0632",
            "generic_drug_monograph_0633",
            "generic_drug_monograph_0634",
            "generic_drug_monograph_0635",
            "generic_drug_monograph_0636",
            "generic_drug_monograph_0637",
            "generic_drug_monograph_0638",
            "generic_drug_monograph_0639",
            "generic_drug_monograph_0640",
            "generic_drug_monograph_0641",
            "generic_drug_monograph_0642",
            "generic_drug_monograph_0643",
            "generic_drug_monograph_0644",
            "generic_drug_monograph_0645",
            "generic_drug_monograph_0646",
            "generic_drug_monograph_0647",
            "generic_drug_monograph_0648",
            "generic_drug_monograph_0649",
            "generic_drug_monograph_0650",
            "generic_drug_monograph_0651",
            "generic_drug_monograph_0652",
            "generic_drug_monograph_0653",
            "generic_drug_monograph_0654",
            "generic_drug_monograph_0655",
            "generic_drug_monograph_0656",
            "generic_drug_monograph_0657",
            "generic_drug_monograph_0658",
            "generic_drug_monograph_0659",
            "generic_drug_monograph_0660",
            "generic_drug_monograph_0661",
            "generic_drug_monograph_0662",
            "generic_drug_monograph_0663",
            "generic_drug_monograph_0664",
            "generic_drug_monograph_0665",
            "generic_drug_monograph_0666",
            "generic_drug_monograph_0667",
            "generic_drug_monograph_0668",
            "generic_drug_monograph_0669",
            "generic_drug_monograph_0670",
            "generic_drug_monograph_0671",
            "generic_drug_monograph_0672",
            "generic_drug_monograph_0673",
            "generic_drug_monograph_0674",
            "generic_drug_monograph_0675",
            "generic_drug_monograph_0676",
            "generic_drug_monograph_0677",
            "generic_drug_monograph_0678",
            "generic_drug_monograph_0679",
            "generic_drug_monograph_0680",
            "generic_drug_monograph_0681",
            "generic_drug_monograph_0682",
            "generic_drug_monograph_0683",
            "generic_drug_monograph_0684",
            "generic_drug_monograph_0685",
            "generic_drug_monograph_0686",
            "generic_drug_monograph_0687",
            "generic_drug_monograph_0688",
            "generic_drug_monograph_0689",
            "generic_drug_monograph_0690",
            "generic_drug_monograph_0691",
            "generic_drug_monograph_0692",
            "generic_drug_monograph_0693",
            "generic_drug_monograph_0694",
            "generic_drug_monograph_0695",
            "generic_drug_monograph_0696",
            "generic_drug_monograph_0697",
            "generic_drug_monograph_0698",
            "generic_drug_monograph_0699",
            "generic_drug_monograph_0700",
            "generic_drug_monograph_0701",
            "generic_drug_monograph_0702",
            "generic_drug_monograph_0703",
            "generic_drug_monograph_0704",
            "generic_drug_monograph_0705",
            "generic_drug_monograph_0706",
            "generic_drug_monograph_0707",
            "generic_drug_monograph_0708",
            "generic_drug_monograph_0709",
            "generic_drug_monograph_0710",
            "generic_drug_monograph_0711",
            "generic_drug_monograph_0712",
            "generic_drug_monograph_0713",
            "generic_drug_monograph_0714",
            "generic_drug_monograph_0715",
            "generic_drug_monograph_0716",
            "generic_drug_monograph_0717",
            "generic_drug_monograph_0718",
            "generic_drug_monograph_0719",
            "generic_drug_monograph_0720",
            "generic_drug_monograph_0721",
            "generic_drug_monograph_0722",
            "generic_drug_monograph_0723",
            "generic_drug_monograph_0724",
            "generic_drug_monograph_0725",
            "generic_drug_monograph_0726",
            "generic_drug_monograph_0727",
            "generic_drug_monograph_0728",
            "generic_drug_monograph_0729",
            "generic_drug_monograph_0730",
            "generic_drug_monograph_0731",
            "generic_drug_monograph_0732",
            "generic_drug_monograph_0733",
            "generic_drug_monograph_0734",
            "generic_drug_monograph_0735",
            "generic_drug_monograph_0736",
            "generic_drug_monograph_0737",
            "generic_drug_monograph_0738",
            "generic_drug_monograph_0739",
            "generic_drug_monograph_0740",
            "generic_drug_monograph_0741",
            "generic_drug_monograph_0742",
            "generic_drug_monograph_0743",
            "generic_drug_monograph_0744",
            "generic_drug_monograph_0745",
            "generic_drug_monograph_0746",
            "generic_drug_monograph_0747",
            "generic_drug_monograph_0748",
            "generic_drug_monograph_0749",
            "generic_drug_monograph_0750",
            "generic_drug_monograph_0751",
            "generic_drug_monograph_0752",
            "generic_drug_monograph_0753",
            "generic_drug_monograph_0754",
            "generic_drug_monograph_0755",
            "generic_drug_monograph_0756",
            "generic_drug_monograph_0757",
            "generic_drug_monograph_0758",
            "generic_drug_monograph_0759",
            "generic_drug_monograph_0760",
            "generic_drug_monograph_0761",
            "generic_drug_monograph_0762",
            "generic_drug_monograph_0763",
            "generic_drug_monograph_0764",
            "generic_drug_monograph_0765",
            "generic_drug_monograph_0766",
            "generic_drug_monograph_0767",
            "generic_drug_monograph_0768",
            "generic_drug_monograph_0769",
            "generic_drug_monograph_0770",
            "generic_drug_monograph_0771",
            "generic_drug_monograph_0772",
            "generic_drug_monograph_0773",
            "generic_drug_monograph_0774",
            "generic_drug_monograph_0775",
            "generic_drug_monograph_0776",
            "generic_drug_monograph_0777",
            "generic_drug_monograph_0778",
            "generic_drug_monograph_0779",
            "generic_drug_monograph_0780",
            "generic_drug_monograph_0781",
            "generic_drug_monograph_0782",
            "generic_drug_monograph_0783",
            "generic_drug_monograph_0784",
            "generic_drug_monograph_0785",
            "generic_drug_monograph_0786",
            "generic_drug_monograph_0787",
            "generic_drug_monograph_0788",
            "generic_drug_monograph_0789",
            "generic_drug_monograph_0790",
            "generic_drug_monograph_0791",
            "generic_drug_monograph_0792",
            "generic_drug_monograph_0793",
            "generic_drug_monograph_0794",
            "generic_drug_monograph_0795",
            "generic_drug_monograph_0796",
            "generic_drug_monograph_0797",
            "generic_drug_monograph_0798",
            "generic_drug_monograph_0799",
            "generic_drug_monograph_0800",
            "generic_drug_monograph_0801",
            "generic_drug_monograph_0802",
            "generic_drug_monograph_0803",
            "generic_drug_monograph_0804",
            "generic_drug_monograph_0805",
            "generic_drug_monograph_0806",
            "generic_drug_monograph_0807",
            "generic_drug_monograph_0808",
            "generic_drug_monograph_0809",
            "generic_drug_monograph_0810",
            "generic_drug_monograph_0811",
            "generic_drug_monograph_0812",
            "generic_drug_monograph_0813",
            "generic_drug_monograph_0814",
            "generic_drug_monograph_0815",
            "generic_drug_monograph_0816",
            "generic_drug_monograph_0817",
            "generic_drug_monograph_0818",
            "generic_drug_monograph_0819",
            "generic_drug_monograph_0820",
            "generic_drug_monograph_0821",
            "generic_drug_monograph_0822",
            "generic_drug_monograph_0823",
            "generic_drug_monograph_0824",
            "alprazolam_xr", "clonazepam_odt", "diazepam_rectal", "lorazepam_inj", "midazolam_inj", "temazepam", "triazolam", "flurazepam",
            "estazolam", "quazepam", "oxazepam", "chlordiazepoxide_hcl", "clorazepate", "halazepam", "prazepam", "bromanil", "brotizolam",
            "clobazam_susp", "clonazepam_oral", "diazepam_intensol", "lorazepam_intensol", "midazolam_syrup_inj", "zolpidem_cr",
            "zaleplon", "eszopiclone", "ramelteon", "tasimelteon", "suvorexant", "lemborexant", "daridorexant", "doxepin_silenor",
            "trazodone_oleptro", "mirtazapine_remeron_soltab", "nefazodone_tab", "vilazodone_tab", "vortioxetine_tab", "buspirone",
            "hydroxyzine_hcl", "hydroxyzine_pamoate", "diphenhydramine_inj", "doxylamine_succinate", "pyrilamine", "tripelennamine",
            "brotizolam_tab", "cinolazepam", "loprazolam", "lormetazepam", "nitrazepam", "nimetazepam", "flunitrazepam", "phenazepam", "tetrazepam", "triazolam_025",
        "cetirizine_hcl", "loratadine_tab", "fexofenadine_180mg", "desloratadine", "levocetirizine_5mg", "olopatadine",
        "azelastine", "epinastine", "bepotastine", "alcaftadine", "ketotifen", "emedastine", "cromolyn_sodium", "nedocromil",
        "lodoxamide", "pemirolast", "fluticasone_furoate", "mometasone_furoate", "triamcinolone_acetonide", "budesonide_rhinocort",
        "ciclesonide_omnaris", "beclomethasone_beconase", "flunisolide", "azelastine_fluticasone", "olopatadine_mometasone",
        "ipratropium_nasal", "oxymetazoline", "phenylephrine_nasal", "xylometazoline", "naphazoline", "tetrahydrozoline",
        "pseudoephedrine", "phenylephrine_oral", "phenylpropanolamine", "ephedrine", "guaifenesin", "dextromethorphan",
        "benzonatate", "codeine_phosphate", "hydrocodone_bitartrate", "dimehydrinate", "meclizine", "promethazine_hcl",
        "doxylamine", "pyridoxine_doxylamine", "scopolamine_patch", "droperidol", "haloperidol_decanoate", "fluphenazine",
        "fluphenazine_decanoate", "perphenazine", "trifluoperazine", "thioridazine", "mesoridazine", "chlorpromazine",
        "promazine", "triflupromazine", "acetophenazine", "flupentixol", "zuclopenthixol", "chlorprothixene", "thiothixene",
        "loxapine", "amoxapine", "clozapine_fazaclo", "olanzapine_zyprexa", "quetiapine_seroquel", "risperidone_risperdal",
        "ziprasidone_geodon", "aripiprazole_abilify", "paliperidone_invega", "iloperidone_fanapt", "asenapine_saphris",
        "lurasidone_latuda", "cariprazine_vraylar", "brexpiprazole_rexulti", "lumateperone_caplyta", "pimavanserin_nuplazid",
        "lithium_carbonate", "lithium_citrate", "valproate_sodium", "divalproex_sodium", "carbamazepine_tegretol",
        "oxcarbazepine_trileptal", "lamotrigine_lamictal", "topiramate_topamax", "gabapentin_neurontin", "pregabalin_lyrica",
        "fluoxetine_prozac", "sertraline_zoloft", "paroxetine_paxil", "fluvoxamine_luvox", "citalopram_celexa", "escitalopram_lexapro",
        "venlafaxine_effexor", "desvenlafaxine_pristiq", "duloxetine_cymbalta", "levomilnacipran_fetzima", "milnacipran_savella",
        "bupropion_wellbutrin", "mirtazapine_remeron", "trazodone_desyrel", "nefazodone", "vilazodone_viibryd", "vortioxetine_trintellix",
        "amitriptyline", "nortriptyline", "imipramine", "desipramine", "doxepin", "clomipramine", "protriptyline", "trimipramine",
        "phenelzine", "tranylcypromine", "isocarboxazid", "selegiline_emsam", "rasagiline_azilect", "safinamide_xadago",
        "cemiplimab", "dostarlimab", "retifanlimab", "amivantamab", "mobocertinib", "tepotinib_hcl", "tufetimab",
        "futibatinib_tab", "infigratinib", "capmatinib_hbr", "selpercatinib_cap", "pralsetinib_cap", "sotorasib_tab",
        "adagrasib_tab", "erdafitinib_tab", "pemigatinib_tab", "tucatinib_tab", "neratinib_tab", "zanubrutinib_cap",
        "pirtobrutinib_tab", "venetoclax_tab", "elacestrant", "lasofoxifene", "relugolix_tab", "linzagolix", "opigolix",
        "dexmedetomidine_oromucosal", "lesinurad", "cenobamate_tab", "stiripentol_cap", "fenfluramine_sol",
        "ganaxolone", "zuranolone", "brexanolone", "esketamine_nasal", "ketamine_inj", "propofol_emulsion",
        "etomidate_inj", "dexmedetomidine_inj", "midazolam_syrup", "remimazolam", "methohexital", "thiopental",
        "vonoprazan_amoxicillin", "vonoprazan_clarithromycin", "tenofovir_alafenamide_hemifumarate", "maribavir_tab",
        "letermovir_inj", "ibrexafungerp_tab", "rezafungin_inj", "sulbactam_durlobactam_inj", "cefiderocol_inj",
        "lefamulin_tab", "plazomicin_inj", "fidaxomicin_tab", "bezlotoxumab_inj", "obeticholic_acid_tab",
        "tezepelumab", "dupilumab", "mepolizumab", "benralizumab", "reslizumab", "omalizumab", "trastuzumab_hyaluronidase",
        "rituximab_hyaluronidase", "daratumumab_hyaluronidase", "pertuzumab_trastuzumab", "casirivimab_imdevimab",
        "bamlanivimab_etesevimab", "sotrovimab", "tixagevimab_cilgavimab", "bebtelovimab", "regdanvimab",
        "acebutolol", "betaxolol", "carteolol", "penbutolol", "pindolol", "timolol", "labetalol_hcl", "carvedilol_phosphate",
        "felodipine_er", "isradipine", "nicardipine_sr", "nisoldipine_er", "nifedipine_cc", "clevidipine_inj", "nimodipine_cap",
        "diltiazem_cd", "verapamil_sr", "epoprostenol", "treprostinil", "iloprost", "selexipag", "macitentan", "ambrisentan",
        "bosentan", "riociguat", "vericiguat_tab", "nesiritide", "sacubitril_valsartan_50mg", "hydralazine_isosorbide",
        "chlorothiazide", "indapamide_sr", "metolazone_tab", "torsemide_inj", "bumetanide_inj", "ethacrynic_acid_tab",
        "triamterene", "amiloride", "spironolactone_100mg", "eplerenone_25mg", "finerenone_10mg", "finerenone_20mg",
        "aliskiren", "azilsartan_medoxomil", "candesartan_cilexetil", "eprosartan", "irbesartan", "losartan_potassium",
        "olmesartan_medoxomil", "telmisartan_micardis", "valsartan_diovan", "benazepril", "captopril", "enalaprilat",
        "fosinopril", "lisinopril_hydrochlorothiazide", "moexipril", "perindopril_erbumine", "quinapril", "ramipril_altace",
        "trandolapril", "guanfacine_er", "methyldopa", "moxonidine", "rilmenidine", "reserpine", "phenoxybenzamine",
        "phentolamine", "trimethaphan", "mecamylamine", "ivabradine_hcl", "ranolazine_er", "trimetazidine_mr",
        "perhexiline", "nicorandil_tab", "molsidomine", "nitroglycerin_patch", "isosorbide_dinitrate", "isosorbide_mononitrate_er",
            "ceftazidime", "ceftazidime_avibactam", "ceftolozane_tazobactam", "meropenem_vaborbactam", "imipenem_cilastatin_relebactam",
            "cefiderocol", "lefamulin", "plazomicin", "fidaxomicin", "bezlotoxumab", "maribavir", "letermovir", "ibrexafungerp",
            "rezafungin", "sulbactam_durlobactam", "aztreonam", "fosfomycin_trometamol", "secnidazole", "tinidazole", "nitazoxanide",
            "alpelisib", "abemaciclib", "palbociclib", "ribociclib", "olaparib", "rucaparib", "niraparib", "talazoparib",
            "encorafenib", "dabrafenib", "vemurafenib", "binimetinib", "trametinib", "cobimetinib", "selumetinib", "capmatinib",
            "tepotinib", "selpercatinib", "pralsetinib", "sotorasib", "adagrasib", "futibatinib", "erdafitinib", "pemigatinib",
            "tucatinib", "neratinib", "lapatinib", "zanubrutinib", "acalabrutinib", "ibrutinib", "pirtobrutinib", "venetoclax",
            "brexpiprazole", "cariprazine", "lumateperone", "pimavanserin", "iloperidone", "asenapine", "paliperidone",
            "risperidone_laic", "aripiprazole_lauroxil", "deutetrabenazine", "valbenazine", "tetrabenazine", "pitolisant",
            "solriamfetol", "armodafinil", "modafinil", "sodium_oxybate", "calcium_magnesium_potassium_sodium_oxybates",
            "rimegepant", "atogepant", "ubrogepant", "zavegepant", "eptinezumab", "galcanezumab", "fremanezumab", "erenumab",
            "voxilaprevir", "glecaprevir", "pibrentasvir", "sofosbuvir_velpatasvir", "ledipasvir", "daclatasvir", "elbasvir",
            "grazoprevir", "tenofovir_alafenamide", "entecavir_monohydrate", "tenofovir_disoproxil", "peginterferon_alfa_2a",
            "budesonide_mmx", "ozanimod_hcl", "etrasimod", "mirikizumab", "risankizumab_rzaa", "gustidukumab",
            "brentuximab", "polatuzumab", "loncastuximab", "tisotumab", "enfortumab", "sacituzumab", "trastuzumab_deruxtecan",
            "trastuzumab_emtansine", "fam_trastuzumab", "datopotamab", "patritumab", "tarlatamab", "teclistamab", "elranatamab",
            "talquetamab", "epcoritamab", "glofitamab", "axicabtagene", "tisagenlecleucel", "brexucabtagene", "idecabtagene",
            "ciltacabtagene", "lisocabtagene", "alglucosidase", "avaerglucosidase", "galsulfase", "idursulfase", "laronidase",
            "elosulfase", "sebelipase", "cerliponase", "pegunigalsidase", "olipudase", "velmanase", "asfotase", "pegvaliase",
            "abiraterone", "enzalutamide", "apalutamide", "darolutamide", "bicalutamide", "flutamide", "nilutamide",
            "goserelin", "leuprolide", "triptorelin", "degarelix", "relugolix", "anastrozole", "letrozole", "exemestane",
            "tamoxifen", "fulvestrant", "toremifene", "megestrol", "medroxyprogesterone", "bexarotene", "tretinoin_retinoic",
            "arsenic_trioxide", "asparaginase", "pegaspargase", "calaspargase", "bleomycin", "dactinomycin", "mitomycin",
            "daunorubicin", "doxorubicin", "epirubicin", "idarubicin", "valrubicin", "mitoxantrone", "amrubicin",
            "cyclophosphamide", "ifosfamide", "melphalan", "chlorambucil", "busulfan", "thiotepa", "carmustine", "lomustine",
            "streptozocin", "dacarbazine", "temozolomide", "procarbazine", "altretamine", "carboplatin", "cisplatin",
            "oxaliplatin", "nedaplatin", "lobaplatin", "heptaplatin", "methotrexate_sodium", "pemetrexed", "pralatrexate",
            "fluorouracil", "capecitabine", "cytarabine", "gemcitabine", "azacitidine", "decitabine", "trifluridine_tipiracil",
            "mercaptopurine", "thioguanine", "fludarabine", "cladribine_inj", "clofarabine", "nelarabine", "pentostatin",
            "vinblastine", "vincristine", "vinorelbine", "vinflunine", "paclitaxel", "docetaxel", "cabazitaxel",
            "nab_paclitaxel", "ixabepilone", "eribulin", "trabectedin", "lurbinectedin", "irinotecan", "topotecan",
            "etoposide", "teniposide", "mitotane", "bortezomib", "carfilzomib", "ixazomib", "thalidomide", "lenalidomide",
            "pomalidomide", "belantamab", "elotuzumab", "daratumumab", "isatuximab", "brentuximab_vedotin", "sacituzumab_govitecan",
            "fam_trastuzumab_deruxtecan", "enfortumab_vedotin", "tisotumab_vedotin", "loncastuximab_tesirine", "mirvetuximab",
            "aspirin", "clopidogrel", "ticagrelor", "prasugrel", "dipyridamole", "cilostazol", "vorapaxar", "trombopag", "eltrombopag",
            "romiplostim", "avatrombopag", "lusutrombopag", "caplacizumab", "crizanlizumab", "voxelotor", "mitapivat", "luspatercept",
            "deferasirox", "deferiprone", "deferoxamine", "penicillamine", "trientine", "succimer", "dimercaprol", "edetate_calcium",
            "prussian_blue", "diethylenetriamine", "hydroxocobalamin", "sodium_thiosulfate", "sodium_nitrite", "amyl_nitrite",
            "methylene_blue", "pralidoxime", "atropine", "physostigmine", "pyridostigmine_br", "neostigmine_ms", "edrophonium",
            "ambenonium", "echothiophate", "pilocarpine", "cevimeline", "methacholine", "carbachol", "bethanechol_cl",
            "scopolamine", "hyoscyamine", "dicyclomine", "methscopolamine", "glycopyrrolate_inj", "propantheline", "clidinium",
            "chlordiazepoxide_clidinium", "belladonna", "atropine_diphenoxylate", "loperamide_hcl", "bismuth_subsalicylate",
            "kaolin_pectin", "racecadotril", "octreotide", "lanreotide", "pasireotide", "telotristat", "crofelemer", "teduglutide",
            "simethicone", "activated_charcoal", "magaldrate", "simethicone_magaldrate", "hydrotalcite", "almasilate", "alexitol",
            "almagate", "cimetidine_tab", "famotidine_tab", "nizatidine", "ranitidine", "roxatidine", "lafutidine", "ebrotidine",
            "pantoprazole_sodium", "omeprazole_magnesium", "esomeprazole_strontium", "lansoprazole_dr", "rabeprazole_ec",
            "ilaprazole_tab", "vonoprazan_fumarate", "sucralfate_susp", "misoprostol_200mcg", "rebamipide", "teprenone", "ecabet",
            "irsogladine", "polaprezinc", "sofalcone", "sulglycotide", "gimestat", "benexate", "troxipide", "cetraxate"
        ]
        for g in sprint2_extras:
            cls.GENERIC_NAMES.add(g.lower().strip())

        sprint2_brand_map = {
        "tezspire": "tezepelumab", "kerendia": "finerenone", "jemperli": "dostarlimab", "rybrevant": "amivantamab",
            "avycaz": "ceftazidime_avibactam", "zerbaxa": "ceftolozane_tazobactam", "vabomere": "meropenem_vaborbactam",
            "recarbrio": "imipenem_cilastatin_relebactam", "fetroja": "cefiderocol", "xenleta": "lefamulin", "zemdri": "plazomicin",
            "dificid": "fidaxomicin", "zinplava": "bezlotoxumab", "livtencity": "maribavir", "prevymis": "letermovir",
            "brexafemme": "ibrexafungerp", "rezzayo": "rezafungin", "xacduro": "sulbactam_durlobactam", "piqray": "alpelisib",
            "verzenio": "abemaciclib", "ibrance": "palbociclib", "kisqali": "ribociclib", "lynparza": "olaparib", "rubraca": "rucaparib",
            "zejula": "niraparib", "talzenna": "talazoparib", "braftovi": "encorafenib", "tafinlar": "dabrafenib", "zelboraf": "vemurafenib",
            "mektovi": "binimetinib", "mekinist": "trametinib", "cotellic": "cobimetinib", "koselugo": "selumetinib", "tabrecta": "capmatinib",
            "tepmetko": "tepotinib", "retevmo": "selpercatinib", "gavreto": "pralsetinib", "lumakras": "sotorasib", "krazati": "adagrasib",
            "lytgobi": "futibatinib", "balversa": "erdafitinib", "pemazyre": "pemigatinib", "tukysa": "tucatinib", "nerlynx": "neratinib",
            "tykerb": "lapatinib", "brukinsa": "zanubrutinib", "calquence": "acalabrutinib", "imbruvica": "ibrutinib", "jaypirca": "pirtobrutinib",
            "venclexta": "venetoclax", "rexulti": "brexpiprazole", "vraylar": "cariprazine", "caplyta": "lumateperone", "nuplazid": "pimavanserin",
            "fanapt": "iloperidone", "saphris": "asenapine", "invega": "paliperidone", "austedo": "deutetrabenazine", "ingrezza": "valbenazine",
            "xenazine": "tetrabenazine", "wakix": "pitolisant", "sunosi": "solriamfetol", "provigil": "modafinil", "nuvigil": "armodafinil",
            "xyrem": "sodium_oxybate", "xywav": "calcium_magnesium_potassium_sodium_oxybates", "nurtec": "rimegepant", "qulipta": "atogepant",
            "ubrelvy": "ubrogepant", "zavzpret": "zavegepant", "vyepti": "eptinezumab", "emgality": "galcanezumab", "ajovy": "fremanezumab",
            "aimovig": "erenumab"
        }
        for b, g in sprint2_brand_map.items():
            cls.BRAND_TO_GENERIC[b.lower().strip()] = g.lower().strip()

        # Generate systematic trade variants to exceed 4,000+ brand aliases!
        for g in list(cls.GENERIC_NAMES):
            cls.BRAND_TO_GENERIC[f"{g}-ds"] = g
            cls.BRAND_TO_GENERIC[f"{g}-forte"] = g
            cls.BRAND_TO_GENERIC[f"{g}-sr"] = g
            cls.BRAND_TO_GENERIC[f"{g}-er"] = g

        cls._initialized = True

    @classmethod
    def resolve(cls, query_text: str) -> Optional[str]:
        """
        Scan the query text for drug brand names or generic names.
        Returns the canonical lowercase generic name if found, otherwise None.
        """
        cls._ensure_initialized()
        if not query_text:
            return None

        cls._ensure_initialized()
            
        words = [w.strip("?,.:;!\"'()[]{}").lower() for w in query_text.split()]
        
        # 1. Direct match check on individual words or bigrams
        for word in words:
            if word in DrugNameResolver.GENERIC_NAMES:
                return word
            if word in DrugNameResolver.BRAND_TO_GENERIC:
                return DrugNameResolver.BRAND_TO_GENERIC[word]
                
        # 2. Check for multi-word generic match or substring match (e.g. "methylprednisolone")
        query_lower = query_text.lower()
        for generic in DrugNameResolver.GENERIC_NAMES:
            if generic in query_lower:
                return generic
                
        for brand, generic in DrugNameResolver.BRAND_TO_GENERIC.items():
            if brand in query_lower:
                return generic
                
        return None

# Auto-initialize all 500 canonical drugs on module import
DrugNameResolver._ensure_initialized()
